import { UserProfile, ClassItem, IndicatorItem, AssessmentTask, AssessmentRecord, AppConfig } from '../types';

export const INITIAL_APP_CONFIG: AppConfig = {
  id: 'app_config',
  appName: 'e-PJOK',
  schoolName: 'SMA NEGERI 1 TEJAKULA',
  motto: 'Sportif, Jujur, dan Menghargai Gerak Teman',
  logoIconPreset: 'activity',
  logoUrl: '',
  updatedAt: new Date().toISOString()
};

export const INITIAL_CLASSES: ClassItem[] = [
  { id: 'class-xi-1', nama: 'XI 1', tingkat: 'XI', jurusan: 'Umum', status: 'aktif' },
  { id: 'class-xi-2', nama: 'XI 2', tingkat: 'XI', jurusan: 'Umum', status: 'aktif' },
  { id: 'class-xi-3', nama: 'XI 3', tingkat: 'XI', jurusan: 'Umum', status: 'aktif' },
  { id: 'class-xi-4', nama: 'XI 4', tingkat: 'XI', jurusan: 'Umum', status: 'aktif' },
  { id: 'class-xi-5', nama: 'XI 5', tingkat: 'XI', jurusan: 'Umum', status: 'aktif' },
  { id: 'class-xi-6', nama: 'XI 6', tingkat: 'XI', jurusan: 'Umum', status: 'aktif' },
  { id: 'class-xi-7', nama: 'XI 7', tingkat: 'XI', jurusan: 'Umum', status: 'aktif' },
  { id: 'class-xi-8', nama: 'XI 8', tingkat: 'XI', jurusan: 'Umum', status: 'aktif' },
  { id: 'class-xi-9', nama: 'XI 9', tingkat: 'XI', jurusan: 'Umum', status: 'aktif' },
];

export const INITIAL_USERS: UserProfile[] = [
  {
    uid: 'guru-nova',
    nama: 'Nova Anggarawan (Guru PJOK)',
    email: 'novaanggarawan88@gmail.com',
    password: 'guru123',
    role: 'guru',
    nip: '198501152010011005',
    status: 'aktif',
    fotoProfil: 'https://images.unsplash.com/photo-1544717305-2782549b5136?w=150&auto=format&fit=crop&q=80',
    createdAt: '2026-09-01T08:00:00.000Z'
  },
  {
    uid: 'guru-1',
    nama: 'Guru PJOK',
    email: 'guru@pjok.sch.id',
    password: 'guru123',
    role: 'guru',
    nip: '198501152010011005',
    status: 'aktif',
    fotoProfil: 'https://images.unsplash.com/photo-1544717305-2782549b5136?w=150&auto=format&fit=crop&q=80',
    createdAt: '2026-09-01T08:00:00.000Z'
  },
  {
    uid: 'guru-2',
    nama: 'Guru PJOK (ianggarawan51)',
    email: 'ianggarawan51@guru.smk.belajar.id',
    password: 'guru123',
    role: 'guru',
    nip: '198805202014021003',
    status: 'aktif',
    fotoProfil: 'https://images.unsplash.com/photo-1544717305-2782549b5136?w=150&auto=format&fit=crop&q=80',
    createdAt: '2026-09-01T08:00:00.000Z'
  },
  // ================= KELAS XI 1 (31 Murid) =================
  {
    uid: 'murid-xi1-7504',
    nama: 'Gede Aditya Peratama',
    nis: '7504',
    kelas: 'XI 1',
    nomorAbsen: '1',
    email: 'gedeadityaperatama@pjok.sch.id',
    password: 'murid123',
    role: 'murid',
    status: 'aktif',
    createdAt: '2026-09-01T08:00:00.000Z'
  },
  {
    uid: 'murid-xi1-7474',
    nama: 'Gede Eric Surya Purnama',
    nis: '7474',
    kelas: 'XI 1',
    nomorAbsen: '2',
    email: 'gedeericsuryapurnama@pjok.sch.id',
    password: 'murid123',
    role: 'murid',
    status: 'aktif',
    createdAt: '2026-09-01T08:00:00.000Z'
  },
  {
    uid: 'murid-xi1-7440',
    nama: 'Gede Reynard Dharma Mahardika',
    nis: '7440',
    kelas: 'XI 1',
    nomorAbsen: '3',
    email: 'gedereynarddharmamahardika@pjok.sch.id',
    password: 'murid123',
    role: 'murid',
    status: 'aktif',
    createdAt: '2026-09-01T08:00:00.000Z'
  },
  {
    uid: 'murid-xi1-7478',
    nama: 'I Gede Mukiadi',
    nis: '7478',
    kelas: 'XI 1',
    nomorAbsen: '4',
    email: 'igedemukiadi@pjok.sch.id',
    password: 'murid123',
    role: 'murid',
    status: 'aktif',
    createdAt: '2026-09-01T08:00:00.000Z'
  },
  {
    uid: 'murid-xi1-7612',
    nama: 'I Komang Nova Andriana',
    nis: '7612',
    kelas: 'XI 1',
    nomorAbsen: '5',
    email: 'ikomangnovaandriana@pjok.sch.id',
    password: 'murid123',
    role: 'murid',
    status: 'aktif',
    createdAt: '2026-09-01T08:00:00.000Z'
  },
  {
    uid: 'murid-xi1-7480',
    nama: 'Ida Ayu Putu Savira Maharani',
    nis: '7480',
    kelas: 'XI 1',
    nomorAbsen: '6',
    email: 'idaayuputusaviramaharani@pjok.sch.id',
    password: 'murid123',
    role: 'murid',
    status: 'aktif',
    createdAt: '2026-09-01T08:00:00.000Z'
  },
  {
    uid: 'murid-xi1-7679',
    nama: 'Kadek Dito Mahendra',
    nis: '7679',
    kelas: 'XI 1',
    nomorAbsen: '7',
    email: 'kadekditomahendra@pjok.sch.id',
    password: 'murid123',
    role: 'murid',
    status: 'aktif',
    createdAt: '2026-09-01T08:00:00.000Z'
  },
  {
    uid: 'murid-xi1-7483',
    nama: 'Kadek Wilma Adhya Kusuma',
    nis: '7483',
    kelas: 'XI 1',
    nomorAbsen: '8',
    email: 'kadekwilmaadhyakusuma@pjok.sch.id',
    password: 'murid123',
    role: 'murid',
    status: 'aktif',
    createdAt: '2026-09-01T08:00:00.000Z'
  },
  {
    uid: 'murid-xi1-7447',
    nama: 'Kenzie Ramdhan Tjhang',
    nis: '7447',
    kelas: 'XI 1',
    nomorAbsen: '9',
    email: 'kenzieramdhantjhang@pjok.sch.id',
    password: 'murid123',
    role: 'murid',
    status: 'aktif',
    createdAt: '2026-09-01T08:00:00.000Z'
  },
  {
    uid: 'murid-xi1-7484',
    nama: 'Ketut Cetra Neo Budiartha',
    nis: '7484',
    kelas: 'XI 1',
    nomorAbsen: '10',
    email: 'ketutcetraneobudiartha@pjok.sch.id',
    password: 'murid123',
    role: 'murid',
    status: 'aktif',
    createdAt: '2026-09-01T08:00:00.000Z'
  },
  {
    uid: 'murid-xi1-7450',
    nama: 'Komang Ayu Mahadewi',
    nis: '7450',
    kelas: 'XI 1',
    nomorAbsen: '11',
    email: 'komangayumahadewi@pjok.sch.id',
    password: 'murid123',
    role: 'murid',
    status: 'aktif',
    createdAt: '2026-09-01T08:00:00.000Z'
  },
  {
    uid: 'murid-xi1-7451',
    nama: 'Komang Bintang Gayatri',
    nis: '7451',
    kelas: 'XI 1',
    nomorAbsen: '12',
    email: 'komangbintanggayatri@pjok.sch.id',
    password: 'murid123',
    role: 'murid',
    status: 'aktif',
    createdAt: '2026-09-01T08:00:00.000Z'
  },
  {
    uid: 'murid-xi1-7721',
    nama: 'Komang Ceriya Ningsih',
    nis: '7721',
    kelas: 'XI 1',
    nomorAbsen: '13',
    email: 'komangceriyaningsih@pjok.sch.id',
    password: 'murid123',
    role: 'murid',
    status: 'aktif',
    createdAt: '2026-09-01T08:00:00.000Z'
  },
  {
    uid: 'murid-xi1-7453',
    nama: 'Komang Dhini Pradnyamita Kesuma',
    nis: '7453',
    kelas: 'XI 1',
    nomorAbsen: '14',
    email: 'komangdhinipradnyamitakesuma@pjok.sch.id',
    password: 'murid123',
    role: 'murid',
    status: 'aktif',
    createdAt: '2026-09-01T08:00:00.000Z'
  },
  {
    uid: 'murid-xi1-7454',
    nama: 'Komang Dian Widyasari',
    nis: '7454',
    kelas: 'XI 1',
    nomorAbsen: '15',
    email: 'komangdianwidyasari@pjok.sch.id',
    password: 'murid123',
    role: 'murid',
    status: 'aktif',
    createdAt: '2026-09-01T08:00:00.000Z'
  },
  {
    uid: 'murid-xi1-7725',
    nama: 'Luh Tina Cahyani',
    nis: '7725',
    kelas: 'XI 1',
    nomorAbsen: '16',
    email: 'luhtinacahyani@pjok.sch.id',
    password: 'murid123',
    role: 'murid',
    status: 'aktif',
    createdAt: '2026-09-01T08:00:00.000Z'
  },
  {
    uid: 'murid-xi1-7630',
    nama: 'Made Dwi Astuti Damayanti',
    nis: '7630',
    kelas: 'XI 1',
    nomorAbsen: '17',
    email: 'madedwiastutidamayanti@pjok.sch.id',
    password: 'murid123',
    role: 'murid',
    status: 'aktif',
    createdAt: '2026-09-01T08:00:00.000Z'
  },
  {
    uid: 'murid-xi1-7696',
    nama: 'Made Gustini',
    nis: '7696',
    kelas: 'XI 1',
    nomorAbsen: '18',
    email: 'madegustini@pjok.sch.id',
    password: 'murid123',
    role: 'murid',
    status: 'aktif',
    createdAt: '2026-09-01T08:00:00.000Z'
  },
  {
    uid: 'murid-xi1-7731',
    nama: 'Made Suyasa',
    nis: '7731',
    kelas: 'XI 1',
    nomorAbsen: '19',
    email: 'madesuyasa@pjok.sch.id',
    password: 'murid123',
    role: 'murid',
    status: 'aktif',
    createdAt: '2026-09-01T08:00:00.000Z'
  },
  {
    uid: 'murid-xi1-7697',
    nama: 'Nadine Azzahra Gauri Jendra',
    nis: '7697',
    kelas: 'XI 1',
    nomorAbsen: '20',
    email: 'nadineazzahragaurijendra@pjok.sch.id',
    password: 'murid123',
    role: 'murid',
    status: 'aktif',
    createdAt: '2026-09-01T08:00:00.000Z'
  },
  {
    uid: 'murid-xi1-7526',
    nama: 'Ni Ketut Kirani Savitri',
    nis: '7526',
    kelas: 'XI 1',
    nomorAbsen: '21',
    email: 'niketutkiranisavitri@pjok.sch.id',
    password: 'murid123',
    role: 'murid',
    status: 'aktif',
    createdAt: '2026-09-01T08:00:00.000Z'
  },
  {
    uid: 'murid-xi1-7665',
    nama: 'Ni Komang Nova Ayu Purwani',
    nis: '7665',
    kelas: 'XI 1',
    nomorAbsen: '22',
    email: 'nikomangnovaayupurwani@pjok.sch.id',
    password: 'murid123',
    role: 'murid',
    status: 'aktif',
    createdAt: '2026-09-01T08:00:00.000Z'
  },
  {
    uid: 'murid-xi1-7496',
    nama: 'Ni Made Asha Caitanya',
    nis: '7496',
    kelas: 'XI 1',
    nomorAbsen: '23',
    email: 'nimadeashacaitanya@pjok.sch.id',
    password: 'murid123',
    role: 'murid',
    status: 'aktif',
    createdAt: '2026-09-01T08:00:00.000Z'
  },
  {
    uid: 'murid-xi1-7497',
    nama: 'Ni Made Avara Cetasa',
    nis: '7497',
    kelas: 'XI 1',
    nomorAbsen: '24',
    email: 'nimadeavaracetasa@pjok.sch.id',
    password: 'murid123',
    role: 'murid',
    status: 'aktif',
    createdAt: '2026-09-01T08:00:00.000Z'
  },
  {
    uid: 'murid-xi1-7700',
    nama: 'Ni Putu Bulan Mulia Febriana',
    nis: '7700',
    kelas: 'XI 1',
    nomorAbsen: '25',
    email: 'niputubulanmuliafebriana@pjok.sch.id',
    password: 'murid123',
    role: 'murid',
    status: 'aktif',
    createdAt: '2026-09-01T08:00:00.000Z'
  },
  {
    uid: 'murid-xi1-7468',
    nama: 'Nyoman Ayu Brinda Vitare',
    nis: '7468',
    kelas: 'XI 1',
    nomorAbsen: '26',
    email: 'nyomanayubrindavitare@pjok.sch.id',
    password: 'murid123',
    role: 'murid',
    status: 'aktif',
    createdAt: '2026-09-01T08:00:00.000Z'
  },
  {
    uid: 'murid-xi1-7499',
    nama: 'Putu Audya Sinthya Dewi',
    nis: '7499',
    kelas: 'XI 1',
    nomorAbsen: '27',
    email: 'putuaudyasinthyadewi@pjok.sch.id',
    password: 'murid123',
    role: 'murid',
    status: 'aktif',
    createdAt: '2026-09-01T08:00:00.000Z'
  },
  {
    uid: 'murid-xi1-7565',
    nama: 'Putu Dinda Cintya Dewi',
    nis: '7565',
    kelas: 'XI 1',
    nomorAbsen: '28',
    email: 'putudindacintyadewi@pjok.sch.id',
    password: 'murid123',
    role: 'murid',
    status: 'aktif',
    createdAt: '2026-09-01T08:00:00.000Z'
  },
  {
    uid: 'murid-xi1-7501',
    nama: 'Putu Egalita Grazina Bendesa Mas',
    nis: '7501',
    kelas: 'XI 1',
    nomorAbsen: '29',
    email: 'putuegalitagrazinabendesamas@pjok.sch.id',
    password: 'murid123',
    role: 'murid',
    status: 'aktif',
    createdAt: '2026-09-01T08:00:00.000Z'
  },
  {
    uid: 'murid-xi1-7734',
    nama: 'Putu Sinta',
    nis: '7734',
    kelas: 'XI 1',
    nomorAbsen: '30',
    email: 'putusinta@pjok.sch.id',
    password: 'murid123',
    role: 'murid',
    status: 'aktif',
    createdAt: '2026-09-01T08:00:00.000Z'
  },
  {
    uid: 'murid-xi1-7503',
    nama: 'Tyo Ferdiansyah',
    nis: '7503',
    kelas: 'XI 1',
    nomorAbsen: '31',
    username: 'tyoferdiansyah',
    email: 'tyoferdiansyah@pjok.sch.id',
    password: 'murid123',
    role: 'murid',
    status: 'aktif',
    createdAt: '2026-09-01T08:00:00.000Z'
  },
  // ================= KELAS XI 2 (34 Murid) =================
  {
    uid: 'murid-xi2-7435',
    nama: 'Ayu Kompiang Juliani',
    nis: '7435',
    kelas: 'XI 2',
    nomorAbsen: '1',
    username: 'ayukompiangjuliani',
    email: 'ayukompiangjuliani@pjok.sch.id',
    password: 'murid123',
    role: 'murid',
    status: 'aktif',
    createdAt: '2026-09-01T08:00:00.000Z'
  },
  {
    uid: 'murid-xi2-7536',
    nama: 'Bagus Made Agus Rezza Mahendra',
    nis: '7536',
    kelas: 'XI 2',
    nomorAbsen: '2',
    username: 'bagusmadeagusrezzamahendra',
    email: 'bagusmadeagusrezzamahendra@pjok.sch.id',
    password: 'murid123',
    role: 'murid',
    status: 'aktif',
    createdAt: '2026-09-01T08:00:00.000Z'
  },
  {
    uid: 'murid-xi2-7437',
    nama: 'Daniella Aprilia Putri',
    nis: '7437',
    kelas: 'XI 2',
    nomorAbsen: '3',
    username: 'daniellaapriliaputri',
    email: 'daniellaapriliaputri@pjok.sch.id',
    password: 'murid123',
    role: 'murid',
    status: 'aktif',
    createdAt: '2026-09-01T08:00:00.000Z'
  },
  {
    uid: 'murid-xi2-7438',
    nama: 'Gede Dhipa Putra Dinata',
    nis: '7438',
    kelas: 'XI 2',
    nomorAbsen: '4',
    username: 'gededhipaputradinata',
    email: 'gededhipaputradinata@pjok.sch.id',
    password: 'murid123',
    role: 'murid',
    status: 'aktif',
    createdAt: '2026-09-01T08:00:00.000Z'
  },
  {
    uid: 'murid-xi2-7439',
    nama: 'Gede Digo Benzu Arta',
    nis: '7439',
    kelas: 'XI 2',
    nomorAbsen: '5',
    username: 'gededigobenzuarta',
    email: 'gededigobenzuarta@pjok.sch.id',
    password: 'murid123',
    role: 'murid',
    status: 'aktif',
    createdAt: '2026-09-01T08:00:00.000Z'
  },
  {
    uid: 'murid-xi2-7441',
    nama: 'Ghrasella Queentya Jeanice',
    nis: '7441',
    kelas: 'XI 2',
    nomorAbsen: '6',
    username: 'ghrasellaqueentyajeanice',
    email: 'ghrasellaqueentyajeanice@pjok.sch.id',
    password: 'murid123',
    role: 'murid',
    status: 'aktif',
    createdAt: '2026-09-01T08:00:00.000Z'
  },
  {
    uid: 'murid-xi2-7442',
    nama: 'Gusti Ayu Ketut Saputri',
    nis: '7442',
    kelas: 'XI 2',
    nomorAbsen: '7',
    username: 'gustiayuketutsaputri',
    email: 'gustiayuketutsaputri@pjok.sch.id',
    password: 'murid123',
    role: 'murid',
    status: 'aktif',
    createdAt: '2026-09-01T08:00:00.000Z'
  },
  {
    uid: 'murid-xi2-7444',
    nama: 'I Gede Dodik Krishna Surya Pratama',
    nis: '7444',
    kelas: 'XI 2',
    nomorAbsen: '8',
    username: 'igededodikkrishnasuryapratama',
    email: 'igededodikkrishnasuryapratama@pjok.sch.id',
    password: 'murid123',
    role: 'murid',
    status: 'aktif',
    createdAt: '2026-09-01T08:00:00.000Z'
  },
  {
    uid: 'murid-xi2-7481',
    nama: 'Kadek Agus Putra Wiguna',
    nis: '7481',
    kelas: 'XI 2',
    nomorAbsen: '9',
    username: 'kadekagusputrawiguna',
    email: 'kadekagusputrawiguna@pjok.sch.id',
    password: 'murid123',
    role: 'murid',
    status: 'aktif',
    createdAt: '2026-09-01T08:00:00.000Z'
  },
  {
    uid: 'murid-xi2-7714',
    nama: 'Kadek Egi Pradita',
    nis: '7714',
    kelas: 'XI 2',
    nomorAbsen: '10',
    username: 'kadekegipradita',
    email: 'kadekegipradita@pjok.sch.id',
    password: 'murid123',
    role: 'murid',
    status: 'aktif',
    createdAt: '2026-09-01T08:00:00.000Z'
  },
  {
    uid: 'murid-xi2-7446',
    nama: 'Kadek Ria Udayani',
    nis: '7446',
    kelas: 'XI 2',
    nomorAbsen: '11',
    username: 'kadekriaudayani',
    email: 'kadekriaudayani@pjok.sch.id',
    password: 'murid123',
    role: 'murid',
    status: 'aktif',
    createdAt: '2026-09-01T08:00:00.000Z'
  },
  {
    uid: 'murid-xi2-7583',
    nama: 'Kadek Sintya Sugiantari',
    nis: '7583',
    kelas: 'XI 2',
    nomorAbsen: '12',
    username: 'kadeksintyasugiantari',
    email: 'kadeksintyasugiantari@pjok.sch.id',
    password: 'murid123',
    role: 'murid',
    status: 'aktif',
    createdAt: '2026-09-01T08:00:00.000Z'
  },
  {
    uid: 'murid-xi2-7547',
    nama: 'Kadek Veni Valentina',
    nis: '7547',
    kelas: 'XI 2',
    nomorAbsen: '13',
    username: 'kadekvenivalentina',
    email: 'kadekvenivalentina@pjok.sch.id',
    password: 'murid123',
    role: 'murid',
    status: 'aktif',
    createdAt: '2026-09-01T08:00:00.000Z'
  },
  {
    uid: 'murid-xi2-7485',
    nama: 'Ketut Gede Ari Saskara',
    nis: '7485',
    kelas: 'XI 2',
    nomorAbsen: '14',
    username: 'ketutgedearisaskara',
    email: 'ketutgedearisaskara@pjok.sch.id',
    password: 'murid123',
    role: 'murid',
    status: 'aktif',
    createdAt: '2026-09-01T08:00:00.000Z'
  },
  {
    uid: 'murid-xi2-7448',
    nama: 'Ketut Gusti Juli Hartawan',
    nis: '7448',
    kelas: 'XI 2',
    nomorAbsen: '15',
    username: 'ketutgustijulihartawan',
    email: 'ketutgustijulihartawan@pjok.sch.id',
    password: 'murid123',
    role: 'murid',
    status: 'aktif',
    createdAt: '2026-09-01T08:00:00.000Z'
  },
  {
    uid: 'murid-xi2-7449',
    nama: 'Ketut Tristan Rahadian',
    nis: '7449',
    kelas: 'XI 2',
    nomorAbsen: '16',
    username: 'ketuttristanrahadian',
    email: 'ketuttristanrahadian@pjok.sch.id',
    password: 'murid123',
    role: 'murid',
    status: 'aktif',
    createdAt: '2026-09-01T08:00:00.000Z'
  },
  {
    uid: 'murid-xi2-7487',
    nama: 'Komang Ngurah Abel',
    nis: '7487',
    kelas: 'XI 2',
    nomorAbsen: '17',
    username: 'komangngurahabel',
    email: 'komangngurahabel@pjok.sch.id',
    password: 'murid123',
    role: 'murid',
    status: 'aktif',
    createdAt: '2026-09-01T08:00:00.000Z'
  },
  {
    uid: 'murid-xi2-7623',
    nama: 'Komang Sukriyanti',
    nis: '7623',
    kelas: 'XI 2',
    nomorAbsen: '18',
    username: 'komangsukriyanti',
    email: 'komangsukriyanti@pjok.sch.id',
    password: 'murid123',
    role: 'murid',
    status: 'aktif',
    createdAt: '2026-09-01T08:00:00.000Z'
  },
  {
    uid: 'murid-xi2-7489',
    nama: 'Luh Eka Ulandari',
    nis: '7489',
    kelas: 'XI 2',
    nomorAbsen: '19',
    username: 'luhekaulandari',
    email: 'luhekaulandari@pjok.sch.id',
    password: 'murid123',
    role: 'murid',
    status: 'aktif',
    createdAt: '2026-09-01T08:00:00.000Z'
  },
  {
    uid: 'murid-xi2-7457',
    nama: 'Luh Elsa Firmayanti',
    nis: '7457',
    kelas: 'XI 2',
    nomorAbsen: '20',
    username: 'luhelsafirmayanti',
    email: 'luhelsafirmayanti@pjok.sch.id',
    password: 'murid123',
    role: 'murid',
    status: 'aktif',
    createdAt: '2026-09-01T08:00:00.000Z'
  },
  {
    uid: 'murid-xi2-7460',
    nama: 'Luh Mahendra Rani',
    nis: '7460',
    kelas: 'XI 2',
    nomorAbsen: '21',
    username: 'luhmahendrarani',
    email: 'luhmahendrarani@pjok.sch.id',
    password: 'murid123',
    role: 'murid',
    status: 'aktif',
    createdAt: '2026-09-01T08:00:00.000Z'
  },
  {
    uid: 'murid-xi2-7461',
    nama: 'Luh Nagita Anggi',
    nis: '7461',
    kelas: 'XI 2',
    nomorAbsen: '22',
    username: 'luhnagitaanggi',
    email: 'luhnagitaanggi@pjok.sch.id',
    password: 'murid123',
    role: 'murid',
    status: 'aktif',
    createdAt: '2026-09-01T08:00:00.000Z'
  },
  {
    uid: 'murid-xi2-7462',
    nama: 'Luh Putu Sintya Wati',
    nis: '7462',
    kelas: 'XI 2',
    nomorAbsen: '23',
    username: 'luhputusintyawati',
    email: 'luhputusintyawati@pjok.sch.id',
    password: 'murid123',
    role: 'murid',
    status: 'aktif',
    createdAt: '2026-09-01T08:00:00.000Z'
  },
  {
    uid: 'murid-xi2-7628',
    nama: 'Luh Sri Febby Wulandari',
    nis: '7628',
    kelas: 'XI 2',
    nomorAbsen: '24',
    username: 'luhsrifebbywulandari',
    email: 'luhsrifebbywulandari@pjok.sch.id',
    password: 'murid123',
    role: 'murid',
    status: 'aktif',
    createdAt: '2026-09-01T08:00:00.000Z'
  },
  {
    uid: 'murid-xi2-7559',
    nama: 'Luh Yuni Arista Dewi',
    nis: '7559',
    kelas: 'XI 2',
    nomorAbsen: '25',
    username: 'luhyuniaristadewi',
    email: 'luhyuniaristadewi@pjok.sch.id',
    password: 'murid123',
    role: 'murid',
    status: 'aktif',
    createdAt: '2026-09-01T08:00:00.000Z'
  },
  {
    uid: 'murid-xi2-7730',
    nama: 'Made Nidji Pebyanata',
    nis: '7730',
    kelas: 'XI 2',
    nomorAbsen: '26',
    username: 'madenidjipebyanata',
    email: 'madenidjipebyanata@pjok.sch.id',
    password: 'murid123',
    role: 'murid',
    status: 'aktif',
    createdAt: '2026-09-01T08:00:00.000Z'
  },
  {
    uid: 'murid-xi2-7523',
    nama: 'Made Restu Mahardika',
    nis: '7523',
    kelas: 'XI 2',
    nomorAbsen: '27',
    username: 'maderestumahardika',
    email: 'maderestumahardika@pjok.sch.id',
    password: 'murid123',
    role: 'murid',
    status: 'aktif',
    createdAt: '2026-09-01T08:00:00.000Z'
  },
  {
    uid: 'murid-xi2-7464',
    nama: 'Nengah Indra Prasetya',
    nis: '7464',
    kelas: 'XI 2',
    nomorAbsen: '28',
    username: 'nengahindraprasetya',
    email: 'nengahindraprasetya@pjok.sch.id',
    password: 'murid123',
    role: 'murid',
    status: 'aktif',
    createdAt: '2026-09-01T08:00:00.000Z'
  },
  {
    uid: 'murid-xi2-7466',
    nama: 'Ni Made Silia Agustini',
    nis: '7466',
    kelas: 'XI 2',
    nomorAbsen: '29',
    username: 'nimadesiliaagustini',
    email: 'nimadesiliaagustini@pjok.sch.id',
    password: 'murid123',
    role: 'murid',
    status: 'aktif',
    createdAt: '2026-09-01T08:00:00.000Z'
  },
  {
    uid: 'murid-xi2-7600',
    nama: 'Nyoman Wiguna',
    nis: '7600',
    kelas: 'XI 2',
    nomorAbsen: '30',
    username: 'nyomanwiguna',
    email: 'nyomanwiguna@pjok.sch.id',
    password: 'murid123',
    role: 'murid',
    status: 'aktif',
    createdAt: '2026-09-01T08:00:00.000Z'
  },
  {
    uid: 'murid-xi2-7601',
    nama: 'Pande Gede Evan Aditya',
    nis: '7601',
    kelas: 'XI 2',
    nomorAbsen: '31',
    username: 'pandegedeevanaditya',
    email: 'pandegedeevanaditya@pjok.sch.id',
    password: 'murid123',
    role: 'murid',
    status: 'aktif',
    createdAt: '2026-09-01T08:00:00.000Z'
  },
  {
    uid: 'murid-xi2-7498',
    nama: 'Putu Agni Wikania',
    nis: '7498',
    kelas: 'XI 2',
    nomorAbsen: '32',
    username: 'putuagniwikania',
    email: 'putuagniwikania@pjok.sch.id',
    password: 'murid123',
    role: 'murid',
    status: 'aktif',
    createdAt: '2026-09-01T08:00:00.000Z'
  },
  {
    uid: 'murid-xi2-7637',
    nama: 'Putu Eksa Anggita Wijaya',
    nis: '7637',
    kelas: 'XI 2',
    nomorAbsen: '33',
    username: 'putueksaanggitawijaya',
    email: 'putueksaanggitawijaya@pjok.sch.id',
    password: 'murid123',
    role: 'murid',
    status: 'aktif',
    createdAt: '2026-09-01T08:00:00.000Z'
  },
  {
    uid: 'murid-xi2-7672',
    nama: 'Wayan Yuandana Dharmada',
    nis: '7672',
    kelas: 'XI 2',
    nomorAbsen: '34',
    username: 'wayanyuandanadharmada',
    email: 'wayanyuandanadharmada@pjok.sch.id',
    password: 'murid123',
    role: 'murid',
    status: 'aktif',
    createdAt: '2026-09-01T08:00:00.000Z'
  },
  // ================= KELAS XI 3 (34 Murid) =================
  {
    uid: 'murid-xi3-7472',
    nama: 'Gede Charlos Putra Sedana',
    nis: '7472',
    kelas: 'XI 3',
    nomorAbsen: '1',
    username: 'gedecharlosputrasedana',
    email: 'gedecharlosputrasedana@pjok.sch.id',
    password: 'murid123',
    role: 'murid',
    status: 'aktif',
    createdAt: '2026-09-01T08:00:00.000Z'
  },
  {
    uid: 'murid-xi3-7542',
    nama: 'Gede Yudi April Yana',
    nis: '7542',
    kelas: 'XI 3',
    nomorAbsen: '2',
    username: 'gedeyudiaprilyana',
    email: 'gedeyudiaprilyana@pjok.sch.id',
    password: 'murid123',
    role: 'murid',
    status: 'aktif',
    createdAt: '2026-09-01T08:00:00.000Z'
  },
  {
    uid: 'murid-xi3-7712',
    nama: 'Kadek Dwi Buana Arta Suta',
    nis: '7712',
    kelas: 'XI 3',
    nomorAbsen: '3',
    username: 'kadekdwibuanaartasuta',
    email: 'kadekdwibuanaartasuta@pjok.sch.id',
    password: 'murid123',
    role: 'murid',
    status: 'aktif',
    createdAt: '2026-09-01T08:00:00.000Z'
  },
  {
    uid: 'murid-xi3-7509',
    nama: 'Kadek Erlangga Putra',
    nis: '7509',
    kelas: 'XI 3',
    nomorAbsen: '4',
    username: 'kadekerlanggaputra',
    email: 'kadekerlanggaputra@pjok.sch.id',
    password: 'murid123',
    role: 'murid',
    status: 'aktif',
    createdAt: '2026-09-01T08:00:00.000Z'
  },
  {
    uid: 'murid-xi3-7513',
    nama: 'Ketut Rama Agustin',
    nis: '7513',
    kelas: 'XI 3',
    nomorAbsen: '5',
    username: 'ketutramaagustin',
    email: 'ketutramaagustin@pjok.sch.id',
    password: 'murid123',
    role: 'murid',
    status: 'aktif',
    createdAt: '2026-09-01T08:00:00.000Z'
  },
  {
    uid: 'murid-xi3-7514',
    nama: 'Ketut Tiva',
    nis: '7514',
    kelas: 'XI 3',
    nomorAbsen: '6',
    username: 'ketuttiva',
    email: 'ketuttiva@pjok.sch.id',
    password: 'murid123',
    role: 'murid',
    status: 'aktif',
    createdAt: '2026-09-01T08:00:00.000Z'
  },
  {
    uid: 'murid-xi3-7550',
    nama: 'Komang Ayu Desya Putri',
    nis: '7550',
    kelas: 'XI 3',
    nomorAbsen: '7',
    username: 'komangayudesyaputri',
    email: 'komangayudesyaputri@pjok.sch.id',
    password: 'murid123',
    role: 'murid',
    status: 'aktif',
    createdAt: '2026-09-01T08:00:00.000Z'
  },
  {
    uid: 'murid-xi3-7516',
    nama: 'Komang Chuacalista',
    nis: '7516',
    kelas: 'XI 3',
    nomorAbsen: '8',
    username: 'komangchuacalista',
    email: 'komangchuacalista@pjok.sch.id',
    password: 'murid123',
    role: 'murid',
    status: 'aktif',
    createdAt: '2026-09-01T08:00:00.000Z'
  },
  {
    uid: 'murid-xi3-7620',
    nama: 'Komang Dian Maharani',
    nis: '7620',
    kelas: 'XI 3',
    nomorAbsen: '9',
    username: 'komangdianmaharani',
    email: 'komangdianmaharani@pjok.sch.id',
    password: 'murid123',
    role: 'murid',
    status: 'aktif',
    createdAt: '2026-09-01T08:00:00.000Z'
  },
  {
    uid: 'murid-xi3-7653',
    nama: 'Komang Rita',
    nis: '7653',
    kelas: 'XI 3',
    nomorAbsen: '10',
    username: 'komangrita',
    email: 'komangrita@pjok.sch.id',
    password: 'murid123',
    role: 'murid',
    status: 'aktif',
    createdAt: '2026-09-01T08:00:00.000Z'
  },
  {
    uid: 'murid-xi3-7518',
    nama: 'Komang Selma Putri',
    nis: '7518',
    kelas: 'XI 3',
    nomorAbsen: '11',
    username: 'komangselmaputri',
    email: 'komangselmaputri@pjok.sch.id',
    password: 'murid123',
    role: 'murid',
    status: 'aktif',
    createdAt: '2026-09-01T08:00:00.000Z'
  },
  {
    uid: 'murid-xi3-7456',
    nama: 'Komang Sujana Triananda',
    nis: '7456',
    kelas: 'XI 3',
    nomorAbsen: '12',
    username: 'komangsujanatriananda',
    email: 'komangsujanatriananda@pjok.sch.id',
    password: 'murid123',
    role: 'murid',
    status: 'aktif',
    createdAt: '2026-09-01T08:00:00.000Z'
  },
  {
    uid: 'murid-xi3-7553',
    nama: 'Komang Widiada',
    nis: '7553',
    kelas: 'XI 3',
    nomorAbsen: '13',
    username: 'komangwidiada',
    email: 'komangwidiada@pjok.sch.id',
    password: 'murid123',
    role: 'murid',
    status: 'aktif',
    createdAt: '2026-09-01T08:00:00.000Z'
  },
  {
    uid: 'murid-xi3-7554',
    nama: 'Komang Yuda Pramana',
    nis: '7554',
    kelas: 'XI 3',
    nomorAbsen: '14',
    username: 'komangyudapramana',
    email: 'komangyudapramana@pjok.sch.id',
    password: 'murid123',
    role: 'murid',
    status: 'aktif',
    createdAt: '2026-09-01T08:00:00.000Z'
  },
  {
    uid: 'murid-xi3-7656',
    nama: 'Luh Devita Wulandari',
    nis: '7656',
    kelas: 'XI 3',
    nomorAbsen: '15',
    username: 'luhdevitawulandari',
    email: 'luhdevitawulandari@pjok.sch.id',
    password: 'murid123',
    role: 'murid',
    status: 'aktif',
    createdAt: '2026-09-01T08:00:00.000Z'
  },
  {
    uid: 'murid-xi3-7657',
    nama: 'Luh Eka Dian Cahyani',
    nis: '7657',
    kelas: 'XI 3',
    nomorAbsen: '16',
    username: 'luhekadiancahyani',
    email: 'luhekadiancahyani@pjok.sch.id',
    password: 'murid123',
    role: 'murid',
    status: 'aktif',
    createdAt: '2026-09-01T08:00:00.000Z'
  },
  {
    uid: 'murid-xi3-7458',
    nama: 'Luh Maesa Manik Tirta Wati',
    nis: '7458',
    kelas: 'XI 3',
    nomorAbsen: '17',
    username: 'luhmaesamaniktirtawati',
    email: 'luhmaesamaniktirtawati@pjok.sch.id',
    password: 'murid123',
    role: 'murid',
    status: 'aktif',
    createdAt: '2026-09-01T08:00:00.000Z'
  },
  {
    uid: 'murid-xi3-7626',
    nama: 'Luh Melty Rismaya Putri',
    nis: '7626',
    kelas: 'XI 3',
    nomorAbsen: '18',
    username: 'luhmeltyrismayaputri',
    email: 'luhmeltyrismayaputri@pjok.sch.id',
    password: 'murid123',
    role: 'murid',
    status: 'aktif',
    createdAt: '2026-09-01T08:00:00.000Z'
  },
  {
    uid: 'murid-xi3-7724',
    nama: 'Luh Novika Yanti',
    nis: '7724',
    kelas: 'XI 3',
    nomorAbsen: '19',
    username: 'luhnovikayanti',
    email: 'luhnovikayanti@pjok.sch.id',
    password: 'murid123',
    role: 'murid',
    status: 'aktif',
    createdAt: '2026-09-01T08:00:00.000Z'
  },
  {
    uid: 'murid-xi3-7591',
    nama: 'Luh Putu Cintya Melani Putri',
    nis: '7591',
    kelas: 'XI 3',
    nomorAbsen: '20',
    username: 'luhputucintyamelaniputri',
    email: 'luhputucintyamelaniputri@pjok.sch.id',
    password: 'murid123',
    role: 'murid',
    status: 'aktif',
    createdAt: '2026-09-01T08:00:00.000Z'
  },
  {
    uid: 'murid-xi3-7627',
    nama: 'Luh Putu Lady Rosa',
    nis: '7627',
    kelas: 'XI 3',
    nomorAbsen: '21',
    username: 'luhputuladyrosa',
    email: 'luhputuladyrosa@pjok.sch.id',
    password: 'murid123',
    role: 'murid',
    status: 'aktif',
    createdAt: '2026-09-01T08:00:00.000Z'
  },
  {
    uid: 'murid-xi3-7520',
    nama: 'Made Karunia Widyari',
    nis: '7520',
    kelas: 'XI 3',
    nomorAbsen: '22',
    username: 'madekaruniawidyari',
    email: 'madekaruniawidyari@pjok.sch.id',
    password: 'murid123',
    role: 'murid',
    status: 'aktif',
    createdAt: '2026-09-01T08:00:00.000Z'
  },
  {
    uid: 'murid-xi3-7521',
    nama: 'Made Nando',
    nis: '7521',
    kelas: 'XI 3',
    nomorAbsen: '23',
    username: 'madenando',
    email: 'madenando@pjok.sch.id',
    password: 'murid123',
    role: 'murid',
    status: 'aktif',
    createdAt: '2026-09-01T08:00:00.000Z'
  },
  {
    uid: 'murid-xi3-7522',
    nama: 'Made Niki Aditya',
    nis: '7522',
    kelas: 'XI 3',
    nomorAbsen: '24',
    username: 'madenikiaditya',
    email: 'madenikiaditya@pjok.sch.id',
    password: 'murid123',
    role: 'murid',
    status: 'aktif',
    createdAt: '2026-09-01T08:00:00.000Z'
  },
  {
    uid: 'murid-xi3-7596',
    nama: 'Nengah Rendyana',
    nis: '7596',
    kelas: 'XI 3',
    nomorAbsen: '25',
    username: 'nengahrendyana',
    email: 'nengahrendyana@pjok.sch.id',
    password: 'murid123',
    role: 'murid',
    status: 'aktif',
    createdAt: '2026-09-01T08:00:00.000Z'
  },
  {
    uid: 'murid-xi3-7632',
    nama: 'Nengah Satria Untara',
    nis: '7632',
    kelas: 'XI 3',
    nomorAbsen: '26',
    username: 'nengahsatriauntara',
    email: 'nengahsatriauntara@pjok.sch.id',
    password: 'murid123',
    role: 'murid',
    status: 'aktif',
    createdAt: '2026-09-01T08:00:00.000Z'
  },
  {
    uid: 'murid-xi3-7737',
    nama: 'Ni Kadek Rena Dwiarta Febriani',
    nis: '7737',
    kelas: 'XI 3',
    nomorAbsen: '27',
    username: 'nikadekrenadwiartafebriani',
    email: 'nikadekrenadwiartafebriani@pjok.sch.id',
    password: 'murid123',
    role: 'murid',
    status: 'aktif',
    createdAt: '2026-09-01T08:00:00.000Z'
  },
  {
    uid: 'murid-xi3-7561',
    nama: 'Ni Kadek Sita Mahadewi',
    nis: '7561',
    kelas: 'XI 3',
    nomorAbsen: '28',
    username: 'nikadeksitamahadewi',
    email: 'nikadeksitamahadewi@pjok.sch.id',
    password: 'murid123',
    role: 'murid',
    status: 'aktif',
    createdAt: '2026-09-01T08:00:00.000Z'
  },
  {
    uid: 'murid-xi3-7495',
    nama: 'Ni Luh Ayu Anggreni Putri',
    nis: '7495',
    kelas: 'XI 3',
    nomorAbsen: '29',
    username: 'niluhayuanggreniputri',
    email: 'niluhayuanggreniputri@pjok.sch.id',
    password: 'murid123',
    role: 'murid',
    status: 'aktif',
    createdAt: '2026-09-01T08:00:00.000Z'
  },
  {
    uid: 'murid-xi3-7634',
    nama: 'Ni Luh Citra Ambar Wati',
    nis: '7634',
    kelas: 'XI 3',
    nomorAbsen: '30',
    username: 'niluhcitraambarwati',
    email: 'niluhcitraambarwati@pjok.sch.id',
    password: 'murid123',
    role: 'murid',
    status: 'aktif',
    createdAt: '2026-09-01T08:00:00.000Z'
  },
  {
    uid: 'murid-xi3-7467',
    nama: 'Ni Putu Ayu Siska Ningrum',
    nis: '7467',
    kelas: 'XI 3',
    nomorAbsen: '31',
    username: 'niputuayusiskaningrum',
    email: 'niputuayusiskaningrum@pjok.sch.id',
    password: 'murid123',
    role: 'murid',
    status: 'aktif',
    createdAt: '2026-09-01T08:00:00.000Z'
  },
  {
    uid: 'murid-xi3-7469',
    nama: 'Nyoman Bayu Juniarta',
    nis: '7469',
    kelas: 'XI 3',
    nomorAbsen: '32',
    username: 'nyomanbayujuniarta',
    email: 'nyomanbayujuniarta@pjok.sch.id',
    password: 'murid123',
    role: 'murid',
    status: 'aktif',
    createdAt: '2026-09-01T08:00:00.000Z'
  },
  {
    uid: 'murid-xi3-7701',
    nama: 'Putu Gangga Aditya Pratama',
    nis: '7701',
    kelas: 'XI 3',
    nomorAbsen: '33',
    username: 'putuganggaadityapratama',
    email: 'putuganggaadityapratama@pjok.sch.id',
    password: 'murid123',
    role: 'murid',
    status: 'aktif',
    createdAt: '2026-09-01T08:00:00.000Z'
  },
  {
    uid: 'murid-xi3-7566',
    nama: 'Putu Kevin Fabio Satyasana Putra',
    nis: '7566',
    kelas: 'XI 3',
    nomorAbsen: '34',
    username: 'putukevinfabiosatyasanaputra',
    email: 'putukevinfabiosatyasanaputra@pjok.sch.id',
    password: 'murid123',
    role: 'murid',
    status: 'aktif',
    createdAt: '2026-09-01T08:00:00.000Z'
  },
  // ================= KELAS XI 4 (34 Murid) =================
  {
    uid: 'murid-xi4-7706',
    nama: 'Gede Dirga Jaya Kusuma',
    nis: '7706',
    kelas: 'XI 4',
    nomorAbsen: '1',
    username: 'gededirgajayakusuma',
    email: 'gededirgajayakusuma@pjok.sch.id',
    password: 'murid123',
    role: 'murid',
    status: 'aktif',
    createdAt: '2026-09-01T08:00:00.000Z'
  },
  {
    uid: 'murid-xi4-7608',
    nama: 'Gede Giri Danendra',
    nis: '7608',
    kelas: 'XI 4',
    nomorAbsen: '2',
    username: 'gedegiridanendra',
    email: 'gedegiridanendra@pjok.sch.id',
    password: 'murid123',
    role: 'murid',
    status: 'aktif',
    createdAt: '2026-09-01T08:00:00.000Z'
  },
  {
    uid: 'murid-xi4-7475',
    nama: 'Gede Lano Surya Raditia',
    nis: '7475',
    kelas: 'XI 4',
    nomorAbsen: '3',
    username: 'gedelanosuryaraditia',
    email: 'gedelanosuryaraditia@pjok.sch.id',
    password: 'murid123',
    role: 'murid',
    status: 'aktif',
    createdAt: '2026-09-01T08:00:00.000Z'
  },
  {
    uid: 'murid-xi4-7541',
    nama: 'Gede Surya Sagita',
    nis: '7541',
    kelas: 'XI 4',
    nomorAbsen: '4',
    username: 'gedesuryasagita',
    email: 'gedesuryasagita@pjok.sch.id',
    password: 'murid123',
    role: 'murid',
    status: 'aktif',
    createdAt: '2026-09-01T08:00:00.000Z'
  },
  {
    uid: 'murid-xi4-7575',
    nama: 'Gede Windu Permana',
    nis: '7575',
    kelas: 'XI 4',
    nomorAbsen: '5',
    username: 'gedewindupermana',
    email: 'gedewindupermana@pjok.sch.id',
    password: 'murid123',
    role: 'murid',
    status: 'aktif',
    createdAt: '2026-09-01T08:00:00.000Z'
  },
  {
    uid: 'murid-xi4-7507',
    nama: 'I Gede Agus Diatmika Supanji',
    nis: '7507',
    kelas: 'XI 4',
    nomorAbsen: '6',
    username: 'igedeagusdiatmikasupanji',
    email: 'igedeagusdiatmikasupanji@pjok.sch.id',
    password: 'murid123',
    role: 'murid',
    status: 'aktif',
    createdAt: '2026-09-01T08:00:00.000Z'
  },
  {
    uid: 'murid-xi4-7479',
    nama: 'I Komang Radyt Sekalan Agneta',
    nis: '7479',
    kelas: 'XI 4',
    nomorAbsen: '7',
    username: 'ikomangradytsekalanagneta',
    email: 'ikomangradytsekalanagneta@pjok.sch.id',
    password: 'murid123',
    role: 'murid',
    status: 'aktif',
    createdAt: '2026-09-01T08:00:00.000Z'
  },
  {
    uid: 'murid-xi4-7579',
    nama: 'Kadek Amira Darma Yanti',
    nis: '7579',
    kelas: 'XI 4',
    nomorAbsen: '8',
    username: 'kadekamiradarmayanti',
    email: 'kadekamiradarmayanti@pjok.sch.id',
    password: 'murid123',
    role: 'murid',
    status: 'aktif',
    createdAt: '2026-09-01T08:00:00.000Z'
  },
  {
    uid: 'murid-xi4-7648',
    nama: 'Ketut Aditia Arya Kori Putra',
    nis: '7648',
    kelas: 'XI 4',
    nomorAbsen: '9',
    username: 'ketutaditiaaryakoriputra',
    email: 'ketutaditiaaryakoriputra@pjok.sch.id',
    password: 'murid123',
    role: 'murid',
    status: 'aktif',
    createdAt: '2026-09-01T08:00:00.000Z'
  },
  {
    uid: 'murid-xi4-7511',
    nama: 'Ketut Bama Kerti',
    nis: '7511',
    kelas: 'XI 4',
    nomorAbsen: '10',
    username: 'ketutbamakerti',
    email: 'ketutbamakerti@pjok.sch.id',
    password: 'murid123',
    role: 'murid',
    status: 'aktif',
    createdAt: '2026-09-01T08:00:00.000Z'
  },
  {
    uid: 'murid-xi4-7584',
    nama: 'Ketut Candra Renita',
    nis: '7584',
    kelas: 'XI 4',
    nomorAbsen: '11',
    username: 'ketutcandrarenita',
    email: 'ketutcandrarenita@pjok.sch.id',
    password: 'murid123',
    role: 'murid',
    status: 'aktif',
    createdAt: '2026-09-01T08:00:00.000Z'
  },
  {
    uid: 'murid-xi4-7585',
    nama: 'Ketut Gesya Pertiwi',
    nis: '7585',
    kelas: 'XI 4',
    nomorAbsen: '12',
    username: 'ketutgesyapertiwi',
    email: 'ketutgesyapertiwi@pjok.sch.id',
    password: 'murid123',
    role: 'murid',
    status: 'aktif',
    createdAt: '2026-09-01T08:00:00.000Z'
  },
  {
    uid: 'murid-xi4-7512',
    nama: 'Ketut Nova Trisna Putri',
    nis: '7512',
    kelas: 'XI 4',
    nomorAbsen: '13',
    username: 'ketutnovatrisnaputri',
    email: 'ketutnovatrisnaputri@pjok.sch.id',
    password: 'murid123',
    role: 'murid',
    status: 'aktif',
    createdAt: '2026-09-01T08:00:00.000Z'
  },
  {
    uid: 'murid-xi4-7685',
    nama: 'Komang Aldi Pradana',
    nis: '7685',
    kelas: 'XI 4',
    nomorAbsen: '14',
    username: 'komangaldipradana',
    email: 'komangaldipradana@pjok.sch.id',
    password: 'murid123',
    role: 'murid',
    status: 'aktif',
    createdAt: '2026-09-01T08:00:00.000Z'
  },
  {
    uid: 'murid-xi4-7654',
    nama: 'Komang Sintia Arioktapiani',
    nis: '7654',
    kelas: 'XI 4',
    nomorAbsen: '15',
    username: 'komangsintiaarioktapiani',
    email: 'komangsintiaarioktapiani@pjok.sch.id',
    password: 'murid123',
    role: 'murid',
    status: 'aktif',
    createdAt: '2026-09-01T08:00:00.000Z'
  },
  {
    uid: 'murid-xi4-7552',
    nama: 'Komang Tri Amanda Satria',
    nis: '7552',
    kelas: 'XI 4',
    nomorAbsen: '16',
    username: 'komangtriamandasatria',
    email: 'komangtriamandasatria@pjok.sch.id',
    password: 'murid123',
    role: 'murid',
    status: 'aktif',
    createdAt: '2026-09-01T08:00:00.000Z'
  },
  {
    uid: 'murid-xi4-7689',
    nama: 'Luh Mei Antari Dewi',
    nis: '7689',
    kelas: 'XI 4',
    nomorAbsen: '17',
    username: 'luhmeiantaridewi',
    email: 'luhmeiantaridewi@pjok.sch.id',
    password: 'murid123',
    role: 'murid',
    status: 'aktif',
    createdAt: '2026-09-01T08:00:00.000Z'
  },
  {
    uid: 'murid-xi4-7519',
    nama: 'Luh Purnama Dewi',
    nis: '7519',
    kelas: 'XI 4',
    nomorAbsen: '18',
    username: 'luhpurnamadewi',
    email: 'luhpurnamadewi@pjok.sch.id',
    password: 'murid123',
    role: 'murid',
    status: 'aktif',
    createdAt: '2026-09-01T08:00:00.000Z'
  },
  {
    uid: 'murid-xi4-7692',
    nama: 'Luh Sintya Widiasih',
    nis: '7692',
    kelas: 'XI 4',
    nomorAbsen: '19',
    username: 'luhsintyawidiasih',
    email: 'luhsintyawidiasih@pjok.sch.id',
    password: 'murid123',
    role: 'murid',
    status: 'aktif',
    createdAt: '2026-09-01T08:00:00.000Z'
  },
  {
    uid: 'murid-xi4-7658',
    nama: 'Luh Trisna Dewi',
    nis: '7658',
    kelas: 'XI 4',
    nomorAbsen: '20',
    username: 'luhtrisnadewi',
    email: 'luhtrisnadewi@pjok.sch.id',
    password: 'murid123',
    role: 'murid',
    status: 'aktif',
    createdAt: '2026-09-01T08:00:00.000Z'
  },
  {
    uid: 'murid-xi4-7727',
    nama: 'Made Ari Mahardika',
    nis: '7727',
    kelas: 'XI 4',
    nomorAbsen: '21',
    username: 'madearimahardika',
    email: 'madearimahardika@pjok.sch.id',
    password: 'murid123',
    role: 'murid',
    status: 'aktif',
    createdAt: '2026-09-01T08:00:00.000Z'
  },
  {
    uid: 'murid-xi4-7659',
    nama: 'Made Indra Yani',
    nis: '7659',
    kelas: 'XI 4',
    nomorAbsen: '22',
    username: 'madeindrayani',
    email: 'madeindrayani@pjok.sch.id',
    password: 'murid123',
    role: 'murid',
    status: 'aktif',
    createdAt: '2026-09-01T08:00:00.000Z'
  },
  {
    uid: 'murid-xi4-7660',
    nama: 'Made Meta Adiari',
    nis: '7660',
    kelas: 'XI 4',
    nomorAbsen: '23',
    username: 'mademetaadiari',
    email: 'mademetaadiari@pjok.sch.id',
    password: 'murid123',
    role: 'murid',
    status: 'aktif',
    createdAt: '2026-09-01T08:00:00.000Z'
  },
  {
    uid: 'murid-xi4-7729',
    nama: 'Made Murti Bharata Niardana',
    nis: '7729',
    kelas: 'XI 4',
    nomorAbsen: '24',
    username: 'mademurtibharataniardana',
    email: 'mademurtibharataniardana@pjok.sch.id',
    password: 'murid123',
    role: 'murid',
    status: 'aktif',
    createdAt: '2026-09-01T08:00:00.000Z'
  },
  {
    uid: 'murid-xi4-7524',
    nama: 'Made Saktiawan Boban',
    nis: '7524',
    kelas: 'XI 4',
    nomorAbsen: '25',
    username: 'madesaktiawanboban',
    email: 'madesaktiawanboban@pjok.sch.id',
    password: 'murid123',
    role: 'murid',
    status: 'aktif',
    createdAt: '2026-09-01T08:00:00.000Z'
  },
  {
    uid: 'murid-xi4-7463',
    nama: 'Made Viona Dwipa Yanti',
    nis: '7463',
    kelas: 'XI 4',
    nomorAbsen: '26',
    username: 'madevionadwipayanti',
    email: 'madevionadwipayanti@pjok.sch.id',
    password: 'murid123',
    role: 'murid',
    status: 'aktif',
    createdAt: '2026-09-01T08:00:00.000Z'
  },
  {
    uid: 'murid-xi4-7664',
    nama: 'Nengah Asana Sangging',
    nis: '7664',
    kelas: 'XI 4',
    nomorAbsen: '27',
    username: 'nengahasanasangging',
    email: 'nengahasanasangging@pjok.sch.id',
    password: 'murid123',
    role: 'murid',
    status: 'aktif',
    createdAt: '2026-09-01T08:00:00.000Z'
  },
  {
    uid: 'murid-xi4-7631',
    nama: 'Nengah Desi Aryantini',
    nis: '7631',
    kelas: 'XI 4',
    nomorAbsen: '28',
    username: 'nengahdesiaryantini',
    email: 'nengahdesiaryantini@pjok.sch.id',
    password: 'murid123',
    role: 'murid',
    status: 'aktif',
    createdAt: '2026-09-01T08:00:00.000Z'
  },
  {
    uid: 'murid-xi4-7528',
    nama: 'Nyoman Sri Triska Yuli',
    nis: '7528',
    kelas: 'XI 4',
    nomorAbsen: '29',
    username: 'nyomansritriskayuli',
    email: 'nyomansritriskayuli@pjok.sch.id',
    password: 'murid123',
    role: 'murid',
    status: 'aktif',
    createdAt: '2026-09-01T08:00:00.000Z'
  },
  {
    uid: 'murid-xi4-7529',
    nama: 'Nyoman Sukmayanti',
    nis: '7529',
    kelas: 'XI 4',
    nomorAbsen: '30',
    username: 'nyomansukmayanti',
    email: 'nyomansukmayanti@pjok.sch.id',
    password: 'murid123',
    role: 'murid',
    status: 'aktif',
    createdAt: '2026-09-01T08:00:00.000Z'
  },
  {
    uid: 'murid-xi4-7500',
    nama: 'Putu Cinta Pracintya',
    nis: '7500',
    kelas: 'XI 4',
    nomorAbsen: '31',
    username: 'putucintapracintya',
    email: 'putucintapracintya@pjok.sch.id',
    password: 'murid123',
    role: 'murid',
    status: 'aktif',
    createdAt: '2026-09-01T08:00:00.000Z'
  },
  {
    uid: 'murid-xi4-7532',
    nama: 'Wayan Eka Widyanti',
    nis: '7532',
    kelas: 'XI 4',
    nomorAbsen: '32',
    username: 'wayanekawidyanti',
    email: 'wayanekawidyanti@pjok.sch.id',
    password: 'murid123',
    role: 'murid',
    status: 'aktif',
    createdAt: '2026-09-01T08:00:00.000Z'
  },
  {
    uid: 'murid-xi4-7533',
    nama: 'Wayan Juliantari',
    nis: '7533',
    kelas: 'XI 4',
    nomorAbsen: '33',
    username: 'wayanjuliantari',
    email: 'wayanjuliantari@pjok.sch.id',
    password: 'murid123',
    role: 'murid',
    status: 'aktif',
    createdAt: '2026-09-01T08:00:00.000Z'
  },
  {
    uid: 'murid-xi4-7534',
    nama: 'Wayan Nadia Sasikirani',
    nis: '7534',
    kelas: 'XI 4',
    nomorAbsen: '34',
    username: 'wayannadiasasikirani',
    email: 'wayannadiasasikirani@pjok.sch.id',
    password: 'murid123',
    role: 'murid',
    status: 'aktif',
    createdAt: '2026-09-01T08:00:00.000Z'
  },
  // ================= KELAS XI 5 (36 Murid) =================
  {
    uid: 'murid-xi5-7470',
    nama: 'Dayu Komang Sukmayani',
    nis: '7470',
    kelas: 'XI 5',
    nomorAbsen: '1',
    username: 'dayukomangsukmayani',
    email: 'dayukomangsukmayani@pjok.sch.id',
    password: 'murid123',
    role: 'murid',
    status: 'aktif',
    createdAt: '2026-09-01T08:00:00.000Z'
  },
  {
    uid: 'murid-xi5-7569',
    nama: 'Gede Andrea Hernanda',
    nis: '7569',
    kelas: 'XI 5',
    nomorAbsen: '2',
    username: 'gedeandreahernanda',
    email: 'gedeandreahernanda@pjok.sch.id',
    password: 'murid123',
    role: 'murid',
    status: 'aktif',
    createdAt: '2026-09-01T08:00:00.000Z'
  },
  {
    uid: 'murid-xi5-7571',
    nama: 'Gede Darma Jaya',
    nis: '7571',
    kelas: 'XI 5',
    nomorAbsen: '3',
    username: 'gededarmajaya',
    email: 'gededarmajaya@pjok.sch.id',
    password: 'murid123',
    role: 'murid',
    status: 'aktif',
    createdAt: '2026-09-01T08:00:00.000Z'
  },
  {
    uid: 'murid-xi5-7476',
    nama: 'Gede Maryo',
    nis: '7476',
    kelas: 'XI 5',
    nomorAbsen: '4',
    username: 'gedemaryo',
    email: 'gedemaryo@pjok.sch.id',
    password: 'murid123',
    role: 'murid',
    status: 'aktif',
    createdAt: '2026-09-01T08:00:00.000Z'
  },
  {
    uid: 'murid-xi5-7539',
    nama: 'Gede Riki Saputra',
    nis: '7539',
    kelas: 'XI 5',
    nomorAbsen: '5',
    username: 'gederikisaputra',
    email: 'gederikisaputra@pjok.sch.id',
    password: 'murid123',
    role: 'murid',
    status: 'aktif',
    createdAt: '2026-09-01T08:00:00.000Z'
  },
  {
    uid: 'murid-xi5-7611',
    nama: 'Gede Rizal Manata',
    nis: '7611',
    kelas: 'XI 5',
    nomorAbsen: '6',
    username: 'gederizalmanata',
    email: 'gederizalmanata@pjok.sch.id',
    password: 'murid123',
    role: 'murid',
    status: 'aktif',
    createdAt: '2026-09-01T08:00:00.000Z'
  },
  {
    uid: 'murid-xi5-7508',
    nama: 'I Made Adi Ermawan',
    nis: '7508',
    kelas: 'XI 5',
    nomorAbsen: '7',
    username: 'imadeadiermawan',
    email: 'imadeadiermawan@pjok.sch.id',
    password: 'murid123',
    role: 'murid',
    status: 'aktif',
    createdAt: '2026-09-01T08:00:00.000Z'
  },
  {
    uid: 'murid-xi5-7677',
    nama: 'I Made Rendy Saputra',
    nis: '7677',
    kelas: 'XI 5',
    nomorAbsen: '8',
    username: 'imaderendysaputra',
    email: 'imaderendysaputra@pjok.sch.id',
    password: 'murid123',
    role: 'murid',
    status: 'aktif',
    createdAt: '2026-09-01T08:00:00.000Z'
  },
  {
    uid: 'murid-xi5-7578',
    nama: 'Ida Komang Yogi Prajanata',
    nis: '7578',
    kelas: 'XI 5',
    nomorAbsen: '9',
    username: 'idakomangyogiprajanata',
    email: 'idakomangyogiprajanata@pjok.sch.id',
    password: 'murid123',
    role: 'murid',
    status: 'aktif',
    createdAt: '2026-09-01T08:00:00.000Z'
  },
  {
    uid: 'murid-xi5-7613',
    nama: 'Kadek Agus Danil Amerta Dwi Putra',
    nis: '7613',
    kelas: 'XI 5',
    nomorAbsen: '10',
    username: 'kadekagusdanilamertadwiputra',
    email: 'kadekagusdanilamertadwiputra@pjok.sch.id',
    password: 'murid123',
    role: 'murid',
    status: 'aktif',
    createdAt: '2026-09-01T08:00:00.000Z'
  },
  {
    uid: 'murid-xi5-7646',
    nama: 'Kadek Alit Kastawan',
    nis: '7646',
    kelas: 'XI 5',
    nomorAbsen: '11',
    username: 'kadekalitkastawan',
    email: 'kadekalitkastawan@pjok.sch.id',
    password: 'murid123',
    role: 'murid',
    status: 'aktif',
    createdAt: '2026-09-01T08:00:00.000Z'
  },
  {
    uid: 'murid-xi5-7581',
    nama: 'Kadek Bayu Riski Putra',
    nis: '7581',
    kelas: 'XI 5',
    nomorAbsen: '12',
    username: 'kadekbayuriskiputra',
    email: 'kadekbayuriskiputra@pjok.sch.id',
    password: 'murid123',
    role: 'murid',
    status: 'aktif',
    createdAt: '2026-09-01T08:00:00.000Z'
  },
  {
    uid: 'murid-xi5-7582',
    nama: 'Kadek Sayu Permata Sari',
    nis: '7582',
    kelas: 'XI 5',
    nomorAbsen: '13',
    username: 'kadeksayupermatasari',
    email: 'kadeksayupermatasari@pjok.sch.id',
    password: 'murid123',
    role: 'murid',
    status: 'aktif',
    createdAt: '2026-09-01T08:00:00.000Z'
  },
  {
    uid: 'murid-xi5-7619',
    nama: 'Kadek Sinta Dewi',
    nis: '7619',
    kelas: 'XI 5',
    nomorAbsen: '14',
    username: 'kadeksintadewi',
    email: 'kadeksintadewi@pjok.sch.id',
    password: 'murid123',
    role: 'murid',
    status: 'aktif',
    createdAt: '2026-09-01T08:00:00.000Z'
  },
  {
    uid: 'murid-xi5-7549',
    nama: 'Ketut Fitrian',
    nis: '7549',
    kelas: 'XI 5',
    nomorAbsen: '15',
    username: 'ketutfitrian',
    email: 'ketutfitrian@pjok.sch.id',
    password: 'murid123',
    role: 'murid',
    status: 'aktif',
    createdAt: '2026-09-01T08:00:00.000Z'
  },
  {
    uid: 'murid-xi5-7515',
    nama: 'Ketut Vivira Rara Rianti',
    nis: '7515',
    kelas: 'XI 5',
    nomorAbsen: '16',
    username: 'ketutvivirarararianti',
    email: 'ketutvivirarararianti@pjok.sch.id',
    password: 'murid123',
    role: 'murid',
    status: 'aktif',
    createdAt: '2026-09-01T08:00:00.000Z'
  },
  {
    uid: 'murid-xi5-7621',
    nama: 'Komang Dwik Widiyasa',
    nis: '7621',
    kelas: 'XI 5',
    nomorAbsen: '17',
    username: 'komangdwikwidiyasa',
    email: 'komangdwikwidiyasa@pjok.sch.id',
    password: 'murid123',
    role: 'murid',
    status: 'aktif',
    createdAt: '2026-09-01T08:00:00.000Z'
  },
  {
    uid: 'murid-xi5-7590',
    nama: 'Komang Sri Trisna Dewi',
    nis: '7590',
    kelas: 'XI 5',
    nomorAbsen: '18',
    username: 'komangsritrisnadewi',
    email: 'komangsritrisnadewi@pjok.sch.id',
    password: 'murid123',
    role: 'murid',
    status: 'aktif',
    createdAt: '2026-09-01T08:00:00.000Z'
  },
  {
    uid: 'murid-xi5-7555',
    nama: 'Luh Aprilia Kartini',
    nis: '7555',
    kelas: 'XI 5',
    nomorAbsen: '19',
    username: 'luhapriliakartini',
    email: 'luhapriliakartini@pjok.sch.id',
    password: 'murid123',
    role: 'murid',
    status: 'aktif',
    createdAt: '2026-09-01T08:00:00.000Z'
  },
  {
    uid: 'murid-xi5-7557',
    nama: 'Luh Eka Swastini',
    nis: '7557',
    kelas: 'XI 5',
    nomorAbsen: '20',
    username: 'luhekaswastini',
    email: 'luhekaswastini@pjok.sch.id',
    password: 'murid123',
    role: 'murid',
    status: 'aktif',
    createdAt: '2026-09-01T08:00:00.000Z'
  },
  {
    uid: 'murid-xi5-7592',
    nama: 'Luh Putu Melly Sutiani',
    nis: '7592',
    kelas: 'XI 5',
    nomorAbsen: '21',
    username: 'luhputumellysutiani',
    email: 'luhputumellysutiani@pjok.sch.id',
    password: 'murid123',
    role: 'murid',
    status: 'aktif',
    createdAt: '2026-09-01T08:00:00.000Z'
  },
  {
    uid: 'murid-xi5-7690',
    nama: 'Luh Putu Ulan Rastini',
    nis: '7690',
    kelas: 'XI 5',
    nomorAbsen: '22',
    username: 'luhputuulanrastini',
    email: 'luhputuulanrastini@pjok.sch.id',
    password: 'murid123',
    role: 'murid',
    status: 'aktif',
    createdAt: '2026-09-01T08:00:00.000Z'
  },
  {
    uid: 'murid-xi5-7558',
    nama: 'Luh Sasti Widiartini',
    nis: '7558',
    kelas: 'XI 5',
    nomorAbsen: '23',
    username: 'luhsastiwidiartini',
    email: 'luhsastiwidiartini@pjok.sch.id',
    password: 'murid123',
    role: 'murid',
    status: 'aktif',
    createdAt: '2026-09-01T08:00:00.000Z'
  },
  {
    uid: 'murid-xi5-7629',
    nama: 'Made Duwi Ariastini',
    nis: '7629',
    kelas: 'XI 5',
    nomorAbsen: '24',
    username: 'madeduwiariastini',
    email: 'madeduwiariastini@pjok.sch.id',
    password: 'murid123',
    role: 'murid',
    status: 'aktif',
    createdAt: '2026-09-01T08:00:00.000Z'
  },
  {
    uid: 'murid-xi5-7661',
    nama: 'Made Monika Devianti',
    nis: '7661',
    kelas: 'XI 5',
    nomorAbsen: '25',
    username: 'mademonikadevianti',
    email: 'mademonikadevianti@pjok.sch.id',
    password: 'murid123',
    role: 'murid',
    status: 'aktif',
    createdAt: '2026-09-01T08:00:00.000Z'
  },
  {
    uid: 'murid-xi5-7663',
    nama: 'Made Wendi Maharta',
    nis: '7663',
    kelas: 'XI 5',
    nomorAbsen: '26',
    username: 'madewendimaharta',
    email: 'madewendimaharta@pjok.sch.id',
    password: 'murid123',
    role: 'murid',
    status: 'aktif',
    createdAt: '2026-09-01T08:00:00.000Z'
  },
  {
    uid: 'murid-xi5-7525',
    nama: 'Ngurah Ketut Danan Jaya Marta Prasetya',
    nis: '7525',
    kelas: 'XI 5',
    nomorAbsen: '27',
    username: 'ngurahketutdananjayamartaprasetya',
    email: 'ngurahketutdananjayamartaprasetya@pjok.sch.id',
    password: 'murid123',
    role: 'murid',
    status: 'aktif',
    createdAt: '2026-09-01T08:00:00.000Z'
  },
  {
    uid: 'murid-xi5-7698',
    nama: 'Ni Kadek Ardina Prasetya',
    nis: '7698',
    kelas: 'XI 5',
    nomorAbsen: '28',
    username: 'nikadekardinaprasetya',
    email: 'nikadekardinaprasetya@pjok.sch.id',
    password: 'murid123',
    role: 'murid',
    status: 'aktif',
    createdAt: '2026-09-01T08:00:00.000Z'
  },
  {
    uid: 'murid-xi5-7562',
    nama: 'Ni Komang Devi Damayanti',
    nis: '7562',
    kelas: 'XI 5',
    nomorAbsen: '29',
    username: 'nikomangdevidamayanti',
    email: 'nikomangdevidamayanti@pjok.sch.id',
    password: 'murid123',
    role: 'murid',
    status: 'aktif',
    createdAt: '2026-09-01T08:00:00.000Z'
  },
  {
    uid: 'murid-xi5-7527',
    nama: 'Ni Komang Sukraeni',
    nis: '7527',
    kelas: 'XI 5',
    nomorAbsen: '30',
    username: 'nikomangsukraeni',
    email: 'nikomangsukraeni@pjok.sch.id',
    password: 'murid123',
    role: 'murid',
    status: 'aktif',
    createdAt: '2026-09-01T08:00:00.000Z'
  },
  {
    uid: 'murid-xi5-7530',
    nama: 'Nyoman Suma Kayla Putri',
    nis: '7530',
    kelas: 'XI 5',
    nomorAbsen: '31',
    username: 'nyomansumakaylaputri',
    email: 'nyomansumakaylaputri@pjok.sch.id',
    password: 'murid123',
    role: 'murid',
    status: 'aktif',
    createdAt: '2026-09-01T08:00:00.000Z'
  },
  {
    uid: 'murid-xi5-7502',
    nama: 'Putu Nitya Nirmala Audia Swandana',
    nis: '7502',
    kelas: 'XI 5',
    nomorAbsen: '32',
    username: 'putunityanirmalaaudiaswandana',
    email: 'putunityanirmalaaudiaswandana@pjok.sch.id',
    password: 'murid123',
    role: 'murid',
    status: 'aktif',
    createdAt: '2026-09-01T08:00:00.000Z'
  },
  {
    uid: 'murid-xi5-7567',
    nama: 'Putu Riski Pajar Pratama',
    nis: '7567',
    kelas: 'XI 5',
    nomorAbsen: '33',
    username: 'puturiskipajarpratama',
    email: 'puturiskipajarpratama@pjok.sch.id',
    password: 'murid123',
    role: 'murid',
    status: 'aktif',
    createdAt: '2026-09-01T08:00:00.000Z'
  },
  {
    uid: 'murid-xi5-7568',
    nama: 'Saskia Aria Oktaviani',
    nis: '7568',
    kelas: 'XI 5',
    nomorAbsen: '34',
    username: 'saskiaariaoktaviani',
    email: 'saskiaariaoktaviani@pjok.sch.id',
    password: 'murid123',
    role: 'murid',
    status: 'aktif',
    createdAt: '2026-09-01T08:00:00.000Z'
  },
  {
    uid: 'murid-xi5-7668',
    nama: 'Wayan Agastya Sangging',
    nis: '7668',
    kelas: 'XI 5',
    nomorAbsen: '35',
    username: 'wayanagastyasangging',
    email: 'wayanagastyasangging@pjok.sch.id',
    password: 'murid123',
    role: 'murid',
    status: 'aktif',
    createdAt: '2026-09-01T08:00:00.000Z'
  },
  {
    uid: 'murid-xi5-7735',
    nama: 'Wayan Suputra Utama Wijaya',
    nis: '7735',
    kelas: 'XI 5',
    nomorAbsen: '36',
    username: 'wayansuputrautamawijaya',
    email: 'wayansuputrautamawijaya@pjok.sch.id',
    password: 'murid123',
    role: 'murid',
    status: 'aktif',
    createdAt: '2026-09-01T08:00:00.000Z'
  },
  // ================= KELAS XI 6 (26 Murid) =================
  {
    uid: 'murid-xi6-7436',
    nama: 'Ayu Nyoman Maha Dewi',
    nis: '7436',
    kelas: 'XI 6',
    nomorAbsen: '1',
    username: 'ayunyomanmahadewi',
    email: 'ayunyomanmahadewi@pjok.sch.id',
    password: 'murid123',
    role: 'murid',
    status: 'aktif',
    createdAt: '2026-09-01T08:00:00.000Z'
  },
  {
    uid: 'murid-xi6-7535',
    nama: 'Bagus Made Adi Pratama',
    nis: '7535',
    kelas: 'XI 6',
    nomorAbsen: '2',
    username: 'bagusmadeadipratama',
    email: 'bagusmadeadipratama@pjok.sch.id',
    password: 'murid123',
    role: 'murid',
    status: 'aktif',
    createdAt: '2026-09-01T08:00:00.000Z'
  },
  {
    uid: 'murid-xi6-7640',
    nama: 'Gede Adika Yoga Brata',
    nis: '7640',
    kelas: 'XI 6',
    nomorAbsen: '3',
    username: 'gedeadikayogabrata',
    email: 'gedeadikayogabrata@pjok.sch.id',
    password: 'murid123',
    role: 'murid',
    status: 'aktif',
    createdAt: '2026-09-01T08:00:00.000Z'
  },
  {
    uid: 'murid-xi6-7641',
    nama: 'Gede Aditya Putra Yasa',
    nis: '7641',
    kelas: 'XI 6',
    nomorAbsen: '4',
    username: 'gedeadityaputrayasa',
    email: 'gedeadityaputrayasa@pjok.sch.id',
    password: 'murid123',
    role: 'murid',
    status: 'aktif',
    createdAt: '2026-09-01T08:00:00.000Z'
  },
  {
    uid: 'murid-xi6-7605',
    nama: 'Gede Arta Wiguna',
    nis: '7605',
    kelas: 'XI 6',
    nomorAbsen: '5',
    username: 'gedeartawiguna',
    email: 'gedeartawiguna@pjok.sch.id',
    password: 'murid123',
    role: 'murid',
    status: 'aktif',
    createdAt: '2026-09-01T08:00:00.000Z'
  },
  {
    uid: 'murid-xi6-7673',
    nama: 'Gede Darma Wibawa',
    nis: '7673',
    kelas: 'XI 6',
    nomorAbsen: '6',
    username: 'gededarmawibawa',
    email: 'gededarmawibawa@pjok.sch.id',
    password: 'murid123',
    role: 'murid',
    status: 'aktif',
    createdAt: '2026-09-01T08:00:00.000Z'
  },
  {
    uid: 'murid-xi6-7736',
    nama: 'Gede Darmawan Saputra',
    nis: '7736',
    kelas: 'XI 6',
    nomorAbsen: '7',
    username: 'gededarmawansaputra',
    email: 'gededarmawansaputra@pjok.sch.id',
    password: 'murid123',
    role: 'murid',
    status: 'aktif',
    createdAt: '2026-09-01T08:00:00.000Z'
  },
  {
    uid: 'murid-xi6-7572',
    nama: 'Gede Gustawan',
    nis: '7572',
    kelas: 'XI 6',
    nomorAbsen: '8',
    username: 'gedegustawan',
    email: 'gedegustawan@pjok.sch.id',
    password: 'murid123',
    role: 'murid',
    status: 'aktif',
    createdAt: '2026-09-01T08:00:00.000Z'
  },
  {
    uid: 'murid-xi6-7707',
    nama: 'Gede Leo Tresna Reza',
    nis: '7707',
    kelas: 'XI 6',
    nomorAbsen: '9',
    username: 'gedeleotresnareza',
    email: 'gedeleotresnareza@pjok.sch.id',
    password: 'murid123',
    role: 'murid',
    status: 'aktif',
    createdAt: '2026-09-01T08:00:00.000Z'
  },
  {
    uid: 'murid-xi6-7477',
    nama: 'Gede Peri Ananta',
    nis: '7477',
    kelas: 'XI 6',
    nomorAbsen: '10',
    username: 'gedeperiananta',
    email: 'gedeperiananta@pjok.sch.id',
    password: 'murid123',
    role: 'murid',
    status: 'aktif',
    createdAt: '2026-09-01T08:00:00.000Z'
  },
  {
    uid: 'murid-xi6-7505',
    nama: 'Gede Rama Aditya Saputra',
    nis: '7505',
    kelas: 'XI 6',
    nomorAbsen: '11',
    username: 'gederamaadityasaputra',
    email: 'gederamaadityasaputra@pjok.sch.id',
    password: 'murid123',
    role: 'murid',
    status: 'aktif',
    createdAt: '2026-09-01T08:00:00.000Z'
  },
  {
    uid: 'murid-xi6-7676',
    nama: 'Gede Suka Yana',
    nis: '7676',
    kelas: 'XI 6',
    nomorAbsen: '12',
    username: 'gedesukayana',
    email: 'gedesukayana@pjok.sch.id',
    password: 'murid123',
    role: 'murid',
    status: 'aktif',
    createdAt: '2026-09-01T08:00:00.000Z'
  },
  {
    uid: 'murid-xi6-7577',
    nama: 'I Komang Tri Arta Adnyana',
    nis: '7577',
    kelas: 'XI 6',
    nomorAbsen: '13',
    username: 'ikomangtriartaadnyana',
    email: 'ikomangtriartaadnyana@pjok.sch.id',
    password: 'murid123',
    role: 'murid',
    status: 'aktif',
    createdAt: '2026-09-01T08:00:00.000Z'
  },
  {
    uid: 'murid-xi6-7709',
    nama: 'I Made Wisnu Dwi Premana',
    nis: '7709',
    kelas: 'XI 6',
    nomorAbsen: '14',
    username: 'imadewisnudwipremana',
    email: 'imadewisnudwipremana@pjok.sch.id',
    password: 'murid123',
    role: 'murid',
    status: 'aktif',
    createdAt: '2026-09-01T08:00:00.000Z'
  },
  {
    uid: 'murid-xi6-7647',
    nama: 'Kadek Sinta Lestari',
    nis: '7647',
    kelas: 'XI 6',
    nomorAbsen: '15',
    username: 'kadeksintalestari',
    email: 'kadeksintalestari@pjok.sch.id',
    password: 'murid123',
    role: 'murid',
    status: 'aktif',
    createdAt: '2026-09-01T08:00:00.000Z'
  },
  {
    uid: 'murid-xi6-7548',
    nama: 'Ketut Devi Ariyanti',
    nis: '7548',
    kelas: 'XI 6',
    nomorAbsen: '16',
    username: 'ketutdeviariyanti',
    email: 'ketutdeviariyanti@pjok.sch.id',
    password: 'murid123',
    role: 'murid',
    status: 'aktif',
    createdAt: '2026-09-01T08:00:00.000Z'
  },
  {
    uid: 'murid-xi6-7515',
    nama: 'Komang Ayu Adiari',
    nis: '7515',
    kelas: 'XI 6',
    nomorAbsen: '17',
    username: 'komangayuadiari',
    email: 'komangayuadiari@pjok.sch.id',
    password: 'murid123',
    role: 'murid',
    status: 'aktif',
    createdAt: '2026-09-01T08:00:00.000Z'
  },
  {
    uid: 'murid-xi6-7452',
    nama: 'Komang Cahaya Tri Pararta',
    nis: '7452',
    kelas: 'XI 6',
    nomorAbsen: '18',
    username: 'komangcahayatripararta',
    email: 'komangcahayatripararta@pjok.sch.id',
    password: 'murid123',
    role: 'murid',
    status: 'aktif',
    createdAt: '2026-09-01T08:00:00.000Z'
  },
  {
    uid: 'murid-xi6-7652',
    nama: 'Komang Juniasih',
    nis: '7652',
    kelas: 'XI 6',
    nomorAbsen: '19',
    username: 'komangjuniasih',
    email: 'komangjuniasih@pjok.sch.id',
    password: 'murid123',
    role: 'murid',
    status: 'aktif',
    createdAt: '2026-09-01T08:00:00.000Z'
  },
  {
    uid: 'murid-xi6-7517',
    nama: 'Komang Santi Dharma Oka',
    nis: '7517',
    kelas: 'XI 6',
    nomorAbsen: '20',
    username: 'komangsantidharmaoka',
    email: 'komangsantidharmaoka@pjok.sch.id',
    password: 'murid123',
    role: 'murid',
    status: 'aktif',
    createdAt: '2026-09-01T08:00:00.000Z'
  },
  {
    uid: 'murid-xi6-7488',
    nama: 'Komang Yuni Astari Devi',
    nis: '7488',
    kelas: 'XI 6',
    nomorAbsen: '21',
    username: 'komangyuniastaridevi',
    email: 'komangyuniastaridevi@pjok.sch.id',
    password: 'murid123',
    role: 'murid',
    status: 'aktif',
    createdAt: '2026-09-01T08:00:00.000Z'
  },
  {
    uid: 'murid-xi6-7688',
    nama: 'Luh Krisnia Sintiya Devi',
    nis: '7688',
    kelas: 'XI 6',
    nomorAbsen: '22',
    username: 'luhkrisniasintiyadevi',
    email: 'luhkrisniasintiyadevi@pjok.sch.id',
    password: 'murid123',
    role: 'murid',
    status: 'aktif',
    createdAt: '2026-09-01T08:00:00.000Z'
  },
  {
    uid: 'murid-xi6-7490',
    nama: 'Luh Lestari',
    nis: '7490',
    kelas: 'XI 6',
    nomorAbsen: '23',
    username: 'luhlestari',
    email: 'luhlestari@pjok.sch.id',
    password: 'murid123',
    role: 'murid',
    status: 'aktif',
    createdAt: '2026-09-01T08:00:00.000Z'
  },
  {
    uid: 'murid-xi6-7459',
    nama: 'Luh Mahayoni',
    nis: '7459',
    kelas: 'XI 6',
    nomorAbsen: '24',
    username: 'luhmahayoni',
    email: 'luhmahayoni@pjok.sch.id',
    password: 'murid123',
    role: 'murid',
    status: 'aktif',
    createdAt: '2026-09-01T08:00:00.000Z'
  },
  {
    uid: 'murid-xi6-7531',
    nama: 'Putu Agus Suryamaja',
    nis: '7531',
    kelas: 'XI 6',
    nomorAbsen: '25',
    username: 'putuagussuryamaja',
    email: 'putuagussuryamaja@pjok.sch.id',
    password: 'murid123',
    role: 'murid',
    status: 'aktif',
    createdAt: '2026-09-01T08:00:00.000Z'
  },
  {
    uid: 'murid-xi6-7638',
    nama: 'Wayan Eka Lestari',
    nis: '7638',
    kelas: 'XI 6',
    nomorAbsen: '26',
    username: 'wayanekalestari',
    email: 'wayanekalestari@pjok.sch.id',
    password: 'murid123',
    role: 'murid',
    status: 'aktif',
    createdAt: '2026-09-01T08:00:00.000Z'
  },
  // ================= KELAS XI 7 (28 Murid) =================
  {
    uid: 'murid-xi7-7604',
    nama: 'Gede Adi Krisna Saputra',
    nis: '7604',
    kelas: 'XI 7',
    nomorAbsen: '1',
    username: 'gedeadikrisnasaputra',
    email: 'gedeadikrisnasaputra@pjok.sch.id',
    password: 'murid123',
    role: 'murid',
    status: 'aktif',
    createdAt: '2026-09-01T08:00:00.000Z'
  },
  {
    uid: 'murid-xi7-7471',
    nama: 'Gede Alit Juni Antara',
    nis: '7471',
    kelas: 'XI 7',
    nomorAbsen: '2',
    username: 'gedealitjuniantara',
    email: 'gedealitjuniantara@pjok.sch.id',
    password: 'murid123',
    role: 'murid',
    status: 'aktif',
    createdAt: '2026-09-01T08:00:00.000Z'
  },
  {
    uid: 'murid-xi7-7607',
    nama: 'Gede Geri Saputra',
    nis: '7607',
    kelas: 'XI 7',
    nomorAbsen: '3',
    username: 'gedegerisaputra',
    email: 'gedegerisaputra@pjok.sch.id',
    password: 'murid123',
    role: 'murid',
    status: 'aktif',
    createdAt: '2026-09-01T08:00:00.000Z'
  },
  {
    uid: 'murid-xi7-7540',
    nama: 'Gede Riskiada',
    nis: '7540',
    kelas: 'XI 7',
    nomorAbsen: '4',
    username: 'gederiskiada',
    email: 'gederiskiada@pjok.sch.id',
    password: 'murid123',
    role: 'murid',
    status: 'aktif',
    createdAt: '2026-09-01T08:00:00.000Z'
  },
  {
    uid: 'murid-xi7-7506',
    nama: 'Gusti Agus Nova Diana Am',
    nis: '7506',
    kelas: 'XI 7',
    nomorAbsen: '5',
    username: 'gustiagusnovadianaam',
    email: 'gustiagusnovadianaam@pjok.sch.id',
    password: 'murid123',
    role: 'murid',
    status: 'aktif',
    createdAt: '2026-09-01T08:00:00.000Z'
  },
  {
    uid: 'murid-xi7-7708',
    nama: 'I Komang Galih Gigih Gahendra',
    nis: '7708',
    kelas: 'XI 7',
    nomorAbsen: '6',
    username: 'ikomanggalihgigihgahendra',
    email: 'ikomanggalihgigihgahendra@pjok.sch.id',
    password: 'murid123',
    role: 'murid',
    status: 'aktif',
    createdAt: '2026-09-01T08:00:00.000Z'
  },
  {
    uid: 'murid-xi7-7678',
    nama: 'Kadek Adi Aryawan',
    nis: '7678',
    kelas: 'XI 7',
    nomorAbsen: '7',
    username: 'kadekadiaryawan',
    email: 'kadekadiaryawan@pjok.sch.id',
    password: 'murid123',
    role: 'murid',
    status: 'aktif',
    createdAt: '2026-09-01T08:00:00.000Z'
  },
  {
    uid: 'murid-xi7-7713',
    nama: 'Kadek Dwi Putrawan',
    nis: '7713',
    kelas: 'XI 7',
    nomorAbsen: '8',
    username: 'kadekdwiputrawan',
    email: 'kadekdwiputrawan@pjok.sch.id',
    password: 'murid123',
    role: 'murid',
    status: 'aktif',
    createdAt: '2026-09-01T08:00:00.000Z'
  },
  {
    uid: 'murid-xi7-7680',
    nama: 'Kadek Dwi Resmawan',
    nis: '7680',
    kelas: 'XI 7',
    nomorAbsen: '9',
    username: 'kadekdwiresmawan',
    email: 'kadekdwiresmawan@pjok.sch.id',
    password: 'murid123',
    role: 'murid',
    status: 'aktif',
    createdAt: '2026-09-01T08:00:00.000Z'
  },
  {
    uid: 'murid-xi7-7715',
    nama: 'Kadek Nopa Yana',
    nis: '7715',
    kelas: 'XI 7',
    nomorAbsen: '10',
    username: 'kadeknopayana',
    email: 'kadeknopayana@pjok.sch.id',
    password: 'murid123',
    role: 'murid',
    status: 'aktif',
    createdAt: '2026-09-01T08:00:00.000Z'
  },
  {
    uid: 'murid-xi7-7510',
    nama: 'Kadek Sariana',
    nis: '7510',
    kelas: 'XI 7',
    nomorAbsen: '11',
    username: 'kadeksariana',
    email: 'kadeksariana@pjok.sch.id',
    password: 'murid123',
    role: 'murid',
    status: 'aktif',
    createdAt: '2026-09-01T08:00:00.000Z'
  },
  {
    uid: 'murid-xi7-7650',
    nama: 'Ketut Kysa Priani',
    nis: '7650',
    kelas: 'XI 7',
    nomorAbsen: '12',
    username: 'ketutkysapriani',
    email: 'ketutkysapriani@pjok.sch.id',
    password: 'murid123',
    role: 'murid',
    status: 'aktif',
    createdAt: '2026-09-01T08:00:00.000Z'
  },
  {
    uid: 'murid-xi7-7719',
    nama: 'Ketut Widya Kristiani',
    nis: '7719',
    kelas: 'XI 7',
    nomorAbsen: '13',
    username: 'ketutwidyakristiani',
    email: 'ketutwidyakristiani@pjok.sch.id',
    password: 'murid123',
    role: 'murid',
    status: 'aktif',
    createdAt: '2026-09-01T08:00:00.000Z'
  },
  {
    uid: 'murid-xi7-7587',
    nama: 'Komang Dila Pebrianti',
    nis: '7587',
    kelas: 'XI 7',
    nomorAbsen: '14',
    username: 'komangdilapebrianti',
    email: 'komangdilapebrianti@pjok.sch.id',
    password: 'murid123',
    role: 'murid',
    status: 'aktif',
    createdAt: '2026-09-01T08:00:00.000Z'
  },
  {
    uid: 'murid-xi7-7588',
    nama: 'Komang Pasek Jaya Artawan',
    nis: '7588',
    kelas: 'XI 7',
    nomorAbsen: '15',
    username: 'komangpasekjayaartawan',
    email: 'komangpasekjayaartawan@pjok.sch.id',
    password: 'murid123',
    role: 'murid',
    status: 'aktif',
    createdAt: '2026-09-01T08:00:00.000Z'
  },
  {
    uid: 'murid-xi7-7551',
    nama: 'Komang Pino Bayu Saputra',
    nis: '7551',
    kelas: 'XI 7',
    nomorAbsen: '16',
    username: 'komangpinobayusaputra',
    email: 'komangpinobayusaputra@pjok.sch.id',
    password: 'murid123',
    role: 'murid',
    status: 'aktif',
    createdAt: '2026-09-01T08:00:00.000Z'
  },
  {
    uid: 'murid-xi7-7655',
    nama: 'Komang Suharta',
    nis: '7655',
    kelas: 'XI 7',
    nomorAbsen: '17',
    username: 'komangsuharta',
    email: 'komangsuharta@pjok.sch.id',
    password: 'murid123',
    role: 'murid',
    status: 'aktif',
    createdAt: '2026-09-01T08:00:00.000Z'
  },
  {
    uid: 'murid-xi7-7556',
    nama: 'Luh Devi Sukma Ardila',
    nis: '7556',
    kelas: 'XI 7',
    nomorAbsen: '18',
    username: 'luhdevisukmaardila',
    email: 'luhdevisukmaardila@pjok.sch.id',
    password: 'murid123',
    role: 'murid',
    status: 'aktif',
    createdAt: '2026-09-01T08:00:00.000Z'
  },
  {
    uid: 'murid-xi7-7624',
    nama: 'Luh Ekayanti',
    nis: '7624',
    kelas: 'XI 7',
    nomorAbsen: '19',
    username: 'luhekayanti',
    email: 'luhekayanti@pjok.sch.id',
    password: 'murid123',
    role: 'murid',
    status: 'aktif',
    createdAt: '2026-09-01T08:00:00.000Z'
  },
  {
    uid: 'murid-xi7-7625',
    nama: 'Luh Manis Sri Ayuni',
    nis: '7625',
    kelas: 'XI 7',
    nomorAbsen: '20',
    username: 'luhmanissriayuni',
    email: 'luhmanissriayuni@pjok.sch.id',
    password: 'murid123',
    role: 'murid',
    status: 'aktif',
    createdAt: '2026-09-01T08:00:00.000Z'
  },
  {
    uid: 'murid-xi7-7691',
    nama: 'Luh Sintya Dewi',
    nis: '7691',
    kelas: 'XI 7',
    nomorAbsen: '21',
    username: 'luhsintyadewi',
    email: 'luhsintyadewi@pjok.sch.id',
    password: 'murid123',
    role: 'murid',
    status: 'aktif',
    createdAt: '2026-09-01T08:00:00.000Z'
  },
  {
    uid: 'murid-xi7-7693',
    nama: 'Luh Wita Sari',
    nis: '7693',
    kelas: 'XI 7',
    nomorAbsen: '22',
    username: 'luhwitasari',
    email: 'luhwitasari@pjok.sch.id',
    password: 'murid123',
    role: 'murid',
    status: 'aktif',
    createdAt: '2026-09-01T08:00:00.000Z'
  },
  {
    uid: 'murid-xi7-7728',
    nama: 'Made Giriana',
    nis: '7728',
    kelas: 'XI 7',
    nomorAbsen: '23',
    username: 'madegiriana',
    email: 'madegiriana@pjok.sch.id',
    password: 'murid123',
    role: 'murid',
    status: 'aktif',
    createdAt: '2026-09-01T08:00:00.000Z'
  },
  {
    uid: 'murid-xi7-7599',
    nama: 'Nyoman Risnawan',
    nis: '7599',
    kelas: 'XI 7',
    nomorAbsen: '24',
    username: 'nyomanrisnawan',
    email: 'nyomanrisnawan@pjok.sch.id',
    password: 'murid123',
    role: 'murid',
    status: 'aktif',
    createdAt: '2026-09-01T08:00:00.000Z'
  },
  {
    uid: 'murid-xi7-7732',
    nama: 'Nyoman Widiadnyani',
    nis: '7732',
    kelas: 'XI 7',
    nomorAbsen: '25',
    username: 'nyomanwidiadnyani',
    email: 'nyomanwidiadnyani@pjok.sch.id',
    password: 'murid123',
    role: 'murid',
    status: 'aktif',
    createdAt: '2026-09-01T08:00:00.000Z'
  },
  {
    uid: 'murid-xi7-7602',
    nama: 'Putu Regita Cahyani',
    nis: '7602',
    kelas: 'XI 7',
    nomorAbsen: '26',
    username: 'puturegitacahyani',
    email: 'puturegitacahyani@pjok.sch.id',
    password: 'murid123',
    role: 'murid',
    status: 'aktif',
    createdAt: '2026-09-01T08:00:00.000Z'
  },
  {
    uid: 'murid-xi7-7670',
    nama: 'Wayan Arma Jaya',
    nis: '7670',
    kelas: 'XI 7',
    nomorAbsen: '27',
    username: 'wayanarmajaya',
    email: 'wayanarmajaya@pjok.sch.id',
    password: 'murid123',
    role: 'murid',
    status: 'aktif',
    createdAt: '2026-09-01T08:00:00.000Z'
  },
  {
    uid: 'murid-xi7-7603',
    nama: 'Wayan Yudi Pratama',
    nis: '7603',
    kelas: 'XI 7',
    nomorAbsen: '28',
    username: 'wayanyudipratama',
    email: 'wayanyudipratama@pjok.sch.id',
    password: 'murid123',
    role: 'murid',
    status: 'aktif',
    createdAt: '2026-09-01T08:00:00.000Z'
  },
  // ================= KELAS XI 8 (35 Murid) =================
  {
    uid: 'murid-xi8-7537',
    nama: 'Gede Dika Restiawan',
    nis: '7537',
    kelas: 'XI 8',
    nomorAbsen: '1',
    username: 'gededikarestiawan',
    email: 'gededikarestiawan@pjok.sch.id',
    password: 'murid123',
    role: 'murid',
    status: 'aktif',
    createdAt: '2026-09-01T08:00:00.000Z'
  },
  {
    uid: 'murid-xi8-7606',
    nama: 'Gede Divo Pramudya Ananta',
    nis: '7606',
    kelas: 'XI 8',
    nomorAbsen: '2',
    username: 'gededivopramudyaananta',
    email: 'gededivopramudyaananta@pjok.sch.id',
    password: 'murid123',
    role: 'murid',
    status: 'aktif',
    createdAt: '2026-09-01T08:00:00.000Z'
  },
  {
    uid: 'murid-xi8-7473',
    nama: 'Gede Eka Mahardika',
    nis: '7473',
    kelas: 'XI 8',
    nomorAbsen: '3',
    username: 'gedeekamahardika',
    email: 'gedeekamahardika@pjok.sch.id',
    password: 'murid123',
    role: 'murid',
    status: 'aktif',
    createdAt: '2026-09-01T08:00:00.000Z'
  },
  {
    uid: 'murid-xi8-7573',
    nama: 'Gede Manadi Junia Pramahasta',
    nis: '7573',
    kelas: 'XI 8',
    nomorAbsen: '4',
    username: 'gedemanadijuniapramahasta',
    email: 'gedemanadijuniapramahasta@pjok.sch.id',
    password: 'murid123',
    role: 'murid',
    status: 'aktif',
    createdAt: '2026-09-01T08:00:00.000Z'
  },
  {
    uid: 'murid-xi8-7576',
    nama: 'I Kadek Ely Dwi Kusuma',
    nis: '7576',
    kelas: 'XI 8',
    nomorAbsen: '5',
    username: 'ikadekelydwikusuma',
    email: 'ikadekelydwikusuma@pjok.sch.id',
    password: 'murid123',
    role: 'murid',
    status: 'aktif',
    createdAt: '2026-09-01T08:00:00.000Z'
  },
  {
    uid: 'murid-xi8-7614',
    nama: 'Kadek Angga Wibawa Putra',
    nis: '7614',
    kelas: 'XI 8',
    nomorAbsen: '6',
    username: 'kadekanggawibawaputra',
    email: 'kadekanggawibawaputra@pjok.sch.id',
    password: 'murid123',
    role: 'murid',
    status: 'aktif',
    createdAt: '2026-09-01T08:00:00.000Z'
  },
  {
    uid: 'murid-xi8-7580',
    nama: 'Kadek Bayu Pradana',
    nis: '7580',
    kelas: 'XI 8',
    nomorAbsen: '7',
    username: 'kadekbayupradana',
    email: 'kadekbayupradana@pjok.sch.id',
    password: 'murid123',
    role: 'murid',
    status: 'aktif',
    createdAt: '2026-09-01T08:00:00.000Z'
  },
  {
    uid: 'murid-xi8-7482',
    nama: 'Kadek Dedi Sumariyasa',
    nis: '7482',
    kelas: 'XI 8',
    nomorAbsen: '8',
    username: 'kadekdedisumariyasa',
    email: 'kadekdedisumariyasa@pjok.sch.id',
    password: 'murid123',
    role: 'murid',
    status: 'aktif',
    createdAt: '2026-09-01T08:00:00.000Z'
  },
  {
    uid: 'murid-xi8-7711',
    nama: 'Kadek Dhyka Rizky Dharmawan',
    nis: '7711',
    kelas: 'XI 8',
    nomorAbsen: '9',
    username: 'kadekdhykarizkydharmawan',
    email: 'kadekdhykarizkydharmawan@pjok.sch.id',
    password: 'murid123',
    role: 'murid',
    status: 'aktif',
    createdAt: '2026-09-01T08:00:00.000Z'
  },
  {
    uid: 'murid-xi8-7681',
    nama: 'Kadek Dwi Saputra',
    nis: '7681',
    kelas: 'XI 8',
    nomorAbsen: '10',
    username: 'kadekdwisaputra',
    email: 'kadekdwisaputra@pjok.sch.id',
    password: 'murid123',
    role: 'murid',
    status: 'aktif',
    createdAt: '2026-09-01T08:00:00.000Z'
  },
  {
    uid: 'murid-xi8-7544',
    nama: 'Kadek Edy Wiguna',
    nis: '7544',
    kelas: 'XI 8',
    nomorAbsen: '11',
    username: 'kadekedywiguna',
    email: 'kadekedywiguna@pjok.sch.id',
    password: 'murid123',
    role: 'murid',
    status: 'aktif',
    createdAt: '2026-09-01T08:00:00.000Z'
  },
  {
    uid: 'murid-xi8-7682',
    nama: 'Kadek Kian Melisya Putri',
    nis: '7682',
    kelas: 'XI 8',
    nomorAbsen: '12',
    username: 'kadekkianmelisyaputri',
    email: 'kadekkianmelisyaputri@pjok.sch.id',
    password: 'murid123',
    role: 'murid',
    status: 'aktif',
    createdAt: '2026-09-01T08:00:00.000Z'
  },
  {
    uid: 'murid-xi8-7617',
    nama: 'Kadek Ryananda Cahya Putra',
    nis: '7617',
    kelas: 'XI 8',
    nomorAbsen: '13',
    username: 'kadekryanandacahyaputra',
    email: 'kadekryanandacahyaputra@pjok.sch.id',
    password: 'murid123',
    role: 'murid',
    status: 'aktif',
    createdAt: '2026-09-01T08:00:00.000Z'
  },
  {
    uid: 'murid-xi8-7618',
    nama: 'Kadek Satria Aridinata Dwitama',
    nis: '7618',
    kelas: 'XI 8',
    nomorAbsen: '14',
    username: 'kadeksatriaaridinatadwitama',
    email: 'kadeksatriaaridinatadwitama@pjok.sch.id',
    password: 'murid123',
    role: 'murid',
    status: 'aktif',
    createdAt: '2026-09-01T08:00:00.000Z'
  },
  {
    uid: 'murid-xi8-7683',
    nama: 'Kadek Shinta Dewi',
    nis: '7683',
    kelas: 'XI 8',
    nomorAbsen: '15',
    username: 'kadekshintadewi',
    email: 'kadekshintadewi@pjok.sch.id',
    password: 'murid123',
    role: 'murid',
    status: 'aktif',
    createdAt: '2026-09-01T08:00:00.000Z'
  },
  {
    uid: 'murid-xi8-7717',
    nama: 'Kadek Suastika',
    nis: '7717',
    kelas: 'XI 8',
    nomorAbsen: '16',
    username: 'kadeksuastika',
    email: 'kadeksuastika@pjok.sch.id',
    password: 'murid123',
    role: 'murid',
    status: 'aktif',
    createdAt: '2026-09-01T08:00:00.000Z'
  },
  {
    uid: 'murid-xi8-7546',
    nama: 'Kadek Sugi Pratama',
    nis: '7546',
    kelas: 'XI 8',
    nomorAbsen: '17',
    username: 'kadeksugipratama',
    email: 'kadeksugipratama@pjok.sch.id',
    password: 'murid123',
    role: 'murid',
    status: 'aktif',
    createdAt: '2026-09-01T08:00:00.000Z'
  },
  {
    uid: 'murid-xi8-7649',
    nama: 'Ketut Juni Sugiantara',
    nis: '7649',
    kelas: 'XI 8',
    nomorAbsen: '18',
    username: 'ketutjunisugiantara',
    email: 'ketutjunisugiantara@pjok.sch.id',
    password: 'murid123',
    role: 'murid',
    status: 'aktif',
    createdAt: '2026-09-01T08:00:00.000Z'
  },
  {
    uid: 'murid-xi8-7720',
    nama: 'Komang Adi Artawan',
    nis: '7720',
    kelas: 'XI 8',
    nomorAbsen: '19',
    username: 'komangadiartawan',
    email: 'komangadiartawan@pjok.sch.id',
    password: 'murid123',
    role: 'murid',
    status: 'aktif',
    createdAt: '2026-09-01T08:00:00.000Z'
  },
  {
    uid: 'murid-xi8-7586',
    nama: 'Komang Adi Veridinata',
    nis: '7586',
    kelas: 'XI 8',
    nomorAbsen: '20',
    username: 'komangadiveridinata',
    email: 'komangadiveridinata@pjok.sch.id',
    password: 'murid123',
    role: 'murid',
    status: 'aktif',
    createdAt: '2026-09-01T08:00:00.000Z'
  },
  {
    uid: 'murid-xi8-7651',
    nama: 'Komang Arimbawa',
    nis: '7651',
    kelas: 'XI 8',
    nomorAbsen: '21',
    username: 'komangarimbawa',
    email: 'komangarimbawa@pjok.sch.id',
    password: 'murid123',
    role: 'murid',
    status: 'aktif',
    createdAt: '2026-09-01T08:00:00.000Z'
  },
  {
    uid: 'murid-xi8-7687',
    nama: 'Komang Maharta',
    nis: '7687',
    kelas: 'XI 8',
    nomorAbsen: '22',
    username: 'komangmaharta',
    email: 'komangmaharta@pjok.sch.id',
    password: 'murid123',
    role: 'murid',
    status: 'aktif',
    createdAt: '2026-09-01T08:00:00.000Z'
  },
  {
    uid: 'murid-xi8-7723',
    nama: 'Komang Sriasih',
    nis: '7723',
    kelas: 'XI 8',
    nomorAbsen: '23',
    username: 'komangsriasih',
    email: 'komangsriasih@pjok.sch.id',
    password: 'murid123',
    role: 'murid',
    status: 'aktif',
    createdAt: '2026-09-01T08:00:00.000Z'
  },
  {
    uid: 'murid-xi8-7491',
    nama: 'Luh Prita Melani Putri',
    nis: '7491',
    kelas: 'XI 8',
    nomorAbsen: '24',
    username: 'luhpritamelaniputri',
    email: 'luhpritamelaniputri@pjok.sch.id',
    password: 'murid123',
    role: 'murid',
    status: 'aktif',
    createdAt: '2026-09-01T08:00:00.000Z'
  },
  {
    uid: 'murid-xi8-7695',
    nama: 'Made Bayu Atita',
    nis: '7695',
    kelas: 'XI 8',
    nomorAbsen: '25',
    username: 'madebayuatita',
    email: 'madebayuatita@pjok.sch.id',
    password: 'murid123',
    role: 'murid',
    status: 'aktif',
    createdAt: '2026-09-01T08:00:00.000Z'
  },
  {
    uid: 'murid-xi8-7560',
    nama: 'Made Zenia Damayanti',
    nis: '7560',
    kelas: 'XI 8',
    nomorAbsen: '26',
    username: 'madezeniadamayanti',
    email: 'madezeniadamayanti@pjok.sch.id',
    password: 'murid123',
    role: 'murid',
    status: 'aktif',
    createdAt: '2026-09-01T08:00:00.000Z'
  },
  {
    uid: 'murid-xi8-7595',
    nama: 'Nengah Artawan',
    nis: '7595',
    kelas: 'XI 8',
    nomorAbsen: '27',
    username: 'nengahartawan',
    email: 'nengahartawan@pjok.sch.id',
    password: 'murid123',
    role: 'murid',
    status: 'aktif',
    createdAt: '2026-09-01T08:00:00.000Z'
  },
  {
    uid: 'murid-xi8-7563',
    nama: 'Ni Luh Dewi Purnama Sari',
    nis: '7563',
    kelas: 'XI 8',
    nomorAbsen: '28',
    username: 'niluhdewipurnamasari',
    email: 'niluhdewipurnamasari@pjok.sch.id',
    password: 'murid123',
    role: 'murid',
    status: 'aktif',
    createdAt: '2026-09-01T08:00:00.000Z'
  },
  {
    uid: 'murid-xi8-7465',
    nama: 'Ni Luh Putu Laksmi',
    nis: '7465',
    kelas: 'XI 8',
    nomorAbsen: '29',
    username: 'niluhputulaksmi',
    email: 'niluhputulaksmi@pjok.sch.id',
    password: 'murid123',
    role: 'murid',
    status: 'aktif',
    createdAt: '2026-09-01T08:00:00.000Z'
  },
  {
    uid: 'murid-xi8-7635',
    nama: 'Nyoman Wardiasa',
    nis: '7635',
    kelas: 'XI 8',
    nomorAbsen: '30',
    username: 'nyomanwardiasa',
    email: 'nyomanwardiasa@pjok.sch.id',
    password: 'murid123',
    role: 'murid',
    status: 'aktif',
    createdAt: '2026-09-01T08:00:00.000Z'
  },
  {
    uid: 'murid-xi8-7636',
    nama: 'Putu Ayu Puri Wahyuningsih',
    nis: '7636',
    kelas: 'XI 8',
    nomorAbsen: '31',
    username: 'putuayupuriwahyuningsih',
    email: 'putuayupuriwahyuningsih@pjok.sch.id',
    password: 'murid123',
    role: 'murid',
    status: 'aktif',
    createdAt: '2026-09-01T08:00:00.000Z'
  },
  {
    uid: 'murid-xi8-7666',
    nama: 'Putu Janu Egarmana',
    nis: '7666',
    kelas: 'XI 8',
    nomorAbsen: '32',
    username: 'putujanuegarmana',
    email: 'putujanuegarmana@pjok.sch.id',
    password: 'murid123',
    role: 'murid',
    status: 'aktif',
    createdAt: '2026-09-01T08:00:00.000Z'
  },
  {
    uid: 'murid-xi8-7667',
    nama: 'Putu Santi Wulandari',
    nis: '7667',
    kelas: 'XI 8',
    nomorAbsen: '33',
    username: 'putusantiwulandari',
    email: 'putusantiwulandari@pjok.sch.id',
    password: 'murid123',
    role: 'murid',
    status: 'aktif',
    createdAt: '2026-09-01T08:00:00.000Z'
  },
  {
    uid: 'murid-xi8-7703',
    nama: 'Wayan Apriani',
    nis: '7703',
    kelas: 'XI 8',
    nomorAbsen: '34',
    username: 'wayanapriani',
    email: 'wayanapriani@pjok.sch.id',
    password: 'murid123',
    role: 'murid',
    status: 'aktif',
    createdAt: '2026-09-01T08:00:00.000Z'
  },
  {
    uid: 'murid-xi8-7671',
    nama: 'Wayan Indra Weda Raditya',
    nis: '7671',
    kelas: 'XI 8',
    nomorAbsen: '35',
    username: 'wayanindrawedaraditya',
    email: 'wayanindrawedaraditya@pjok.sch.id',
    password: 'murid123',
    role: 'murid',
    status: 'aktif',
    createdAt: '2026-09-01T08:00:00.000Z'
  },
  // ================= KELAS XI 9 (34 Murid) =================
  {
    uid: 'murid-xi9-7705',
    nama: 'Awallul Fadhilah',
    nis: '7705',
    kelas: 'XI 9',
    nomorAbsen: '1',
    username: 'awallulfadhilah',
    email: 'awallulfadhilah@pjok.sch.id',
    password: 'murid123',
    role: 'murid',
    status: 'aktif',
    createdAt: '2026-09-01T08:00:00.000Z'
  },
  {
    uid: 'murid-xi9-7642',
    nama: 'Gede Agus Pratama',
    nis: '7642',
    kelas: 'XI 9',
    nomorAbsen: '2',
    username: 'gedeaguspratama',
    email: 'gedeaguspratama@pjok.sch.id',
    password: 'murid123',
    role: 'murid',
    status: 'aktif',
    createdAt: '2026-09-01T08:00:00.000Z'
  },
  {
    uid: 'murid-xi9-7570',
    nama: 'Gede Bayu Ananta Pratama',
    nis: '7570',
    kelas: 'XI 9',
    nomorAbsen: '3',
    username: 'gedebayuanantapratama',
    email: 'gedebayuanantapratama@pjok.sch.id',
    password: 'murid123',
    role: 'murid',
    status: 'aktif',
    createdAt: '2026-09-01T08:00:00.000Z'
  },
  {
    uid: 'murid-xi9-7674',
    nama: 'Gede Eka Aditya',
    nis: '7674',
    kelas: 'XI 9',
    nomorAbsen: '4',
    username: 'gedeekaaditya',
    email: 'gedeekaaditya@pjok.sch.id',
    password: 'murid123',
    role: 'murid',
    status: 'aktif',
    createdAt: '2026-09-01T08:00:00.000Z'
  },
  {
    uid: 'murid-xi9-7643',
    nama: 'Gede Jaya Mustika',
    nis: '7643',
    kelas: 'XI 9',
    nomorAbsen: '5',
    username: 'gedejayamustika',
    email: 'gedejayamustika@pjok.sch.id',
    password: 'murid123',
    role: 'murid',
    status: 'aktif',
    createdAt: '2026-09-01T08:00:00.000Z'
  },
  {
    uid: 'murid-xi9-7609',
    nama: 'Gede Kristian Revaldi',
    nis: '7609',
    kelas: 'XI 9',
    nomorAbsen: '6',
    username: 'gedekristianrevaldi',
    email: 'gedekristianrevaldi@pjok.sch.id',
    password: 'murid123',
    role: 'murid',
    status: 'aktif',
    createdAt: '2026-09-01T08:00:00.000Z'
  },
  {
    uid: 'murid-xi9-7610',
    nama: 'Gede Putu Galih Adnyana',
    nis: '7610',
    kelas: 'XI 9',
    nomorAbsen: '7',
    username: 'gedeputugalihadnyana',
    email: 'gedeputugalihadnyana@pjok.sch.id',
    password: 'murid123',
    role: 'murid',
    status: 'aktif',
    createdAt: '2026-09-01T08:00:00.000Z'
  },
  {
    uid: 'murid-xi9-7538',
    nama: 'Gede Revan Indrawan',
    nis: '7538',
    kelas: 'XI 9',
    nomorAbsen: '8',
    username: 'gederevanindrawan',
    email: 'gederevanindrawan@pjok.sch.id',
    password: 'murid123',
    role: 'murid',
    status: 'aktif',
    createdAt: '2026-09-01T08:00:00.000Z'
  },
  {
    uid: 'murid-xi9-7574',
    nama: 'Gede Widi Artana',
    nis: '7574',
    kelas: 'XI 9',
    nomorAbsen: '9',
    username: 'gedewidiartana',
    email: 'gedewidiartana@pjok.sch.id',
    password: 'murid123',
    role: 'murid',
    status: 'aktif',
    createdAt: '2026-09-01T08:00:00.000Z'
  },
  {
    uid: 'murid-xi9-7644',
    nama: 'Gede Widia Nata',
    nis: '7644',
    kelas: 'XI 9',
    nomorAbsen: '10',
    username: 'gedewidianata',
    email: 'gedewidianata@pjok.sch.id',
    password: 'murid123',
    role: 'murid',
    status: 'aktif',
    createdAt: '2026-09-01T08:00:00.000Z'
  },
  {
    uid: 'murid-xi9-7645',
    nama: 'I Komang Vedly Ariasa',
    nis: '7645',
    kelas: 'XI 9',
    nomorAbsen: '11',
    username: 'ikomangvedlyariasa',
    email: 'ikomangvedlyariasa@pjok.sch.id',
    password: 'murid123',
    role: 'murid',
    status: 'aktif',
    createdAt: '2026-09-01T08:00:00.000Z'
  },
  {
    uid: 'murid-xi9-7445',
    nama: 'Kadek Ana Muliawati',
    nis: '7445',
    kelas: 'XI 9',
    nomorAbsen: '12',
    username: 'kadekanamuliawati',
    email: 'kadekanamuliawati@pjok.sch.id',
    password: 'murid123',
    role: 'murid',
    status: 'aktif',
    createdAt: '2026-09-01T08:00:00.000Z'
  },
  {
    uid: 'murid-xi9-7710',
    nama: 'Kadek Andika Wiradana',
    nis: '7710',
    kelas: 'XI 9',
    nomorAbsen: '13',
    username: 'kadekandikawiradana',
    email: 'kadekandikawiradana@pjok.sch.id',
    password: 'murid123',
    role: 'murid',
    status: 'aktif',
    createdAt: '2026-09-01T08:00:00.000Z'
  },
  {
    uid: 'murid-xi9-7543',
    nama: 'Kadek Arpel Preti Sara',
    nis: '7543',
    kelas: 'XI 9',
    nomorAbsen: '14',
    username: 'kadekarpelpretisara',
    email: 'kadekarpelpretisara@pjok.sch.id',
    password: 'murid123',
    role: 'murid',
    status: 'aktif',
    createdAt: '2026-09-01T08:00:00.000Z'
  },
  {
    uid: 'murid-xi9-7615',
    nama: 'Kadek Coky Andika Yana',
    nis: '7615',
    kelas: 'XI 9',
    nomorAbsen: '15',
    username: 'kadekcokyandikayana',
    email: 'kadekcokyandikayana@pjok.sch.id',
    password: 'murid123',
    role: 'murid',
    status: 'aktif',
    createdAt: '2026-09-01T08:00:00.000Z'
  },
  {
    uid: 'murid-xi9-7616',
    nama: 'Kadek Okta Anantia',
    nis: '7616',
    kelas: 'XI 9',
    nomorAbsen: '16',
    username: 'kadekoktaanantia',
    email: 'kadekoktaanantia@pjok.sch.id',
    password: 'murid123',
    role: 'murid',
    status: 'aktif',
    createdAt: '2026-09-01T08:00:00.000Z'
  },
  {
    uid: 'murid-xi9-7684',
    nama: 'Kadek Yudi Artawan',
    nis: '7684',
    kelas: 'XI 9',
    nomorAbsen: '17',
    username: 'kadekyudiartawan',
    email: 'kadekyudiartawan@pjok.sch.id',
    password: 'murid123',
    role: 'murid',
    status: 'aktif',
    createdAt: '2026-09-01T08:00:00.000Z'
  },
  {
    uid: 'murid-xi9-7718',
    nama: 'Ketut Widiapermana Putra',
    nis: '7718',
    kelas: 'XI 9',
    nomorAbsen: '18',
    username: 'ketutwidiapermanaputra',
    email: 'ketutwidiapermanaputra@pjok.sch.id',
    password: 'murid123',
    role: 'murid',
    status: 'aktif',
    createdAt: '2026-09-01T08:00:00.000Z'
  },
  {
    uid: 'murid-xi9-7486',
    nama: 'Komang Digo Setiawan',
    nis: '7486',
    kelas: 'XI 9',
    nomorAbsen: '19',
    username: 'komangdigosetiawan',
    email: 'komangdigosetiawan@pjok.sch.id',
    password: 'murid123',
    role: 'murid',
    status: 'aktif',
    createdAt: '2026-09-01T08:00:00.000Z'
  },
  {
    uid: 'murid-xi9-7686',
    nama: 'Komang Gede Satria Candra Bimantara',
    nis: '7686',
    kelas: 'XI 9',
    nomorAbsen: '20',
    username: 'komanggedesatriacandrabimantara',
    email: 'komanggedesatriacandrabimantara@pjok.sch.id',
    password: 'murid123',
    role: 'murid',
    status: 'aktif',
    createdAt: '2026-09-01T08:00:00.000Z'
  },
  {
    uid: 'murid-xi9-7589',
    nama: 'Komang Sandi Olia',
    nis: '7589',
    kelas: 'XI 9',
    nomorAbsen: '21',
    username: 'komangsandiolia',
    email: 'komangsandiolia@pjok.sch.id',
    password: 'murid123',
    role: 'murid',
    status: 'aktif',
    createdAt: '2026-09-01T08:00:00.000Z'
  },
  {
    uid: 'murid-xi9-7694',
    nama: 'Luh Yuna Nova Yanti',
    nis: '7694',
    kelas: 'XI 9',
    nomorAbsen: '22',
    username: 'luhyunanovayanti',
    email: 'luhyunanovayanti@pjok.sch.id',
    password: 'murid123',
    role: 'murid',
    status: 'aktif',
    createdAt: '2026-09-01T08:00:00.000Z'
  },
  {
    uid: 'murid-xi9-7726',
    nama: 'Made Andi Dwi Saputra',
    nis: '7726',
    kelas: 'XI 9',
    nomorAbsen: '23',
    username: 'madeandidwisaputra',
    email: 'madeandidwisaputra@pjok.sch.id',
    password: 'murid123',
    role: 'murid',
    status: 'aktif',
    createdAt: '2026-09-01T08:00:00.000Z'
  },
  {
    uid: 'murid-xi9-7594',
    nama: 'Made Kori Artawan',
    nis: '7594',
    kelas: 'XI 9',
    nomorAbsen: '24',
    username: 'madekoriartawan',
    email: 'madekoriartawan@pjok.sch.id',
    password: 'murid123',
    role: 'murid',
    status: 'aktif',
    createdAt: '2026-09-01T08:00:00.000Z'
  },
  {
    uid: 'murid-xi9-7662',
    nama: 'Made Rendra Gunawan',
    nis: '7662',
    kelas: 'XI 9',
    nomorAbsen: '25',
    username: 'maderendragunawan',
    email: 'maderendragunawan@pjok.sch.id',
    password: 'murid123',
    role: 'murid',
    status: 'aktif',
    createdAt: '2026-09-01T08:00:00.000Z'
  },
  {
    uid: 'murid-xi9-7633',
    nama: 'Ni Ketut Ica Melia Heni',
    nis: '7633',
    kelas: 'XI 9',
    nomorAbsen: '26',
    username: 'niketuticameliaheni',
    email: 'niketuticameliaheni@pjok.sch.id',
    password: 'murid123',
    role: 'murid',
    status: 'aktif',
    createdAt: '2026-09-01T08:00:00.000Z'
  },
  {
    uid: 'murid-xi9-7597',
    nama: 'Ni Ketut Saha Dewi Arini',
    nis: '7597',
    kelas: 'XI 9',
    nomorAbsen: '27',
    username: 'niketutsahadewiarini',
    email: 'niketutsahadewiarini@pjok.sch.id',
    password: 'murid123',
    role: 'murid',
    status: 'aktif',
    createdAt: '2026-09-01T08:00:00.000Z'
  },
  {
    uid: 'murid-xi9-7699',
    nama: 'Ni Luh Ari Muliani',
    nis: '7699',
    kelas: 'XI 9',
    nomorAbsen: '28',
    username: 'niluharimuliani',
    email: 'niluharimuliani@pjok.sch.id',
    password: 'murid123',
    role: 'murid',
    status: 'aktif',
    createdAt: '2026-09-01T08:00:00.000Z'
  },
  {
    uid: 'murid-xi9-7564',
    nama: 'Ni Luh Nindya Ayoni',
    nis: '7564',
    kelas: 'XI 9',
    nomorAbsen: '29',
    username: 'niluhnindyaayoni',
    email: 'niluhnindyaayoni@pjok.sch.id',
    password: 'murid123',
    role: 'murid',
    status: 'aktif',
    createdAt: '2026-09-01T08:00:00.000Z'
  },
  {
    uid: 'murid-xi9-7598',
    nama: 'Ni Luh Nopi Krisna Dewi',
    nis: '7598',
    kelas: 'XI 9',
    nomorAbsen: '30',
    username: 'niluhnopikrisnadewi',
    email: 'niluhnopikrisnadewi@pjok.sch.id',
    password: 'murid123',
    role: 'murid',
    status: 'aktif',
    createdAt: '2026-09-01T08:00:00.000Z'
  },
  {
    uid: 'murid-xi9-7733',
    nama: 'Putu Bayu Pratama',
    nis: '7733',
    kelas: 'XI 9',
    nomorAbsen: '31',
    username: 'putubayupratama',
    email: 'putubayupratama@pjok.sch.id',
    password: 'murid123',
    role: 'murid',
    status: 'aktif',
    createdAt: '2026-09-01T08:00:00.000Z'
  },
  {
    uid: 'murid-xi9-7702',
    nama: 'Putu Ngurah Widiatmaja',
    nis: '7702',
    kelas: 'XI 9',
    nomorAbsen: '32',
    username: 'putungurahwidiatmaja',
    email: 'putungurahwidiatmaja@pjok.sch.id',
    password: 'murid123',
    role: 'murid',
    status: 'aktif',
    createdAt: '2026-09-01T08:00:00.000Z'
  },
  {
    uid: 'murid-xi9-7669',
    nama: 'Wayan Agus Sudarma Artha Sangging',
    nis: '7669',
    kelas: 'XI 9',
    nomorAbsen: '33',
    username: 'wayanagussudarmaarthasangging',
    email: 'wayanagussudarmaarthasangging@pjok.sch.id',
    password: 'murid123',
    role: 'murid',
    status: 'aktif',
    createdAt: '2026-09-01T08:00:00.000Z'
  },
  {
    uid: 'murid-xi9-7704',
    nama: 'Wayan Widi Januarta',
    nis: '7704',
    kelas: 'XI 9',
    nomorAbsen: '34',
    username: 'wayanwidijanuarta',
    email: 'wayanwidijanuarta@pjok.sch.id',
    password: 'murid123',
    role: 'murid',
    status: 'aktif',
    createdAt: '2026-09-01T08:00:00.000Z'
  }
];

export const INITIAL_INDICATORS: IndicatorItem[] = [
  {
    id: 'ind-1',
    judulPenilaian: 'Teknik Passing Bola Basket',
    materi: 'Passing Bola Basket',
    indikator: '1. Sikap awal (posisi tubuh siap, seimbang, dan lutut sedikit ditekuk)',
    urutan: 1,
    status: 'aktif',
    createdAt: '2026-09-10T08:00:00.000Z',
    skala: {
      1: 'Perlu Bimbingan (Kaki kaku, tubuh tegak tanpa persiapan)',
      2: 'Mulai Berkembang (Lutut ditekuk namun keseimbangan kurang stabil)',
      3: 'Baik (Sikap tubuh seimbang, kaki selebar bahu)',
      4: 'Sangat Baik (Sikap sempurna, rileks, siap menerima & memantul)'
    }
  },
  {
    id: 'ind-2',
    judulPenilaian: 'Teknik Passing Bola Basket',
    materi: 'Passing Bola Basket',
    indikator: '2. Posisi kedua tangan memegang bola di depan dada dengan jari terbuka',
    urutan: 2,
    status: 'aktif',
    createdAt: '2026-09-10T08:00:00.000Z',
    skala: {
      1: 'Perlu Bimbingan (Pegang bola tidak pas, jari merapat)',
      2: 'Mulai Berkembang (Pegang bola di depan dada tapi siku melebar)',
      3: 'Baik (Kedua tangan memegang bola tepat di depan dada)',
      4: 'Sangat Baik (Pegang mantap, jari merekah, siku dekat badan)'
    }
  },
  {
    id: 'ind-3',
    judulPenilaian: 'Teknik Passing Bola Basket',
    materi: 'Passing Bola Basket',
    indikator: '3. Gerakan mendorong bola lurus ke depan dengan meluruskan siku',
    urutan: 3,
    status: 'aktif',
    createdAt: '2026-09-10T08:00:00.000Z',
    skala: {
      1: 'Perlu Bimbingan (Dorongan lemah atau bola melambung tinggi)',
      2: 'Mulai Berkembang (Dorongan cukup namun arah bola kurang datar)',
      3: 'Baik (Dorongan kuat dan terarah lurus ke dada kawan)',
      4: 'Sangat Baik (Dorongan cepat, bertenaga, pergelangan tangan lentur)'
    }
  },
  {
    id: 'ind-4',
    judulPenilaian: 'Teknik Passing Bola Basket',
    materi: 'Passing Bola Basket',
    indikator: '4. Arah pandangan fokus tertuju ke dada teman target operan',
    urutan: 4,
    status: 'aktif',
    createdAt: '2026-09-10T08:00:00.000Z',
    skala: {
      1: 'Perlu Bimbingan (Pandangan melihat lantai atau bola)',
      2: 'Mulai Berkembang (Melihat target namun sering teralihkan)',
      3: 'Baik (Fokus melihat target operan dengan jelas)',
      4: 'Sangat Baik (Kontak mata mantap dan membaca posisi teman sasaran)'
    }
  },
  {
    id: 'ind-5',
    judulPenilaian: 'Teknik Passing Bola Basket',
    materi: 'Passing Bola Basket',
    indikator: '5. Gerakan lanjutan (follow through) kedua telapak tangan menghadap keluar',
    urutan: 5,
    status: 'aktif',
    createdAt: '2026-09-10T08:00:00.000Z',
    skala: {
      1: 'Perlu Bimbingan (Tidak ada follow through setelah lepas bola)',
      2: 'Mulai Berkembang (Tangan terlurus tapi telapak belum memutar)',
      3: 'Baik (Kedua lengan lurus, telapak tangan menghadap keluar)',
      4: 'Sangat Baik (Lengan rileks lurus sempurna, ibu jari menghadap ke bawah)'
    }
  }
];

export const INITIAL_TASKS: AssessmentTask[] = [];

export const INITIAL_ASSESSMENTS: AssessmentRecord[] = [];

export const INITIAL_QUIZZES: any[] = [];

export const INITIAL_MATERIALS: any[] = [];

export const INITIAL_LEARNING_TASKS: any[] = [];



